// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Media.Animation {
public class Animatable: global::Compatlib.System.Windows.Freezable {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Animation.Animatable: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Animation.Animatable: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Animation.Animatable]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Animation.Animatable]

} // end of class: Animatable

} // end of namespace: Compatlib.System.Windows.Media.Animation
