// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Threading {
public class Dispatcher: global::Compatlib.System.Object {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher: void <init>()]
}

public virtual void BeginInvoke(global::Compatlib.System.Action n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher: void BeginInvoke(Compatlib.System.Action)]
    dispatcher.BeginInvoke(n1.action);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher: void BeginInvoke(Compatlib.System.Action)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher]
public global::System.Windows.Threading.Dispatcher dispatcher;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Threading.Dispatcher]

} // end of class: Dispatcher

} // end of namespace: Compatlib.System.Windows.Threading
