// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Threading {
public class DispatcherObject: global::Compatlib.System.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Threading.DispatcherObject: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Threading.DispatcherObject: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Threading.DispatcherObject]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Threading.DispatcherObject]

} // end of class: DispatcherObject

} // end of namespace: Compatlib.System.Windows.Threading
