// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Media {
public class Colors: global::Compatlib.System.Object {

static Colors() {
    @static();
}

public static global::Compatlib.System.Windows.Media.Color _fWhite;

public static global::Compatlib.System.Windows.Media.Color _fBlue;

public static global::Compatlib.System.Windows.Media.Color _fBlack;

public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors: void <init>()]
}

public static void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors: void <clinit>()]
    _fWhite = (Color) Color.FromRgb(0xFF, 0xFF, 0xFF);
    _fBlue = (Color) Color.FromRgb(0x00, 0x00, 0xFF);
    _fBlack = (Color) Color.FromRgb(0x00, 0x00, 0x00);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Colors]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Colors]

} // end of class: Colors

} // end of namespace: Compatlib.System.Windows.Media
