// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Media {
public class FontFamily: global::Compatlib.System.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.FontFamily: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.FontFamily: void <init>()]
}

public virtual global::System.Object getSource(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.FontFamily: Compatlib.System.String getSource()]
    return null;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.FontFamily: Compatlib.System.String getSource()]
}

public virtual void setSource(Compatlib.System.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.FontFamily: void setSource(Compatlib.System.String)]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.FontFamily: void setSource(Compatlib.System.String)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.FontFamily]
public global::System.Windows.Media.FontFamily fontFamily;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.FontFamily]

} // end of class: FontFamily

} // end of namespace: Compatlib.System.Windows.Media
