// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Media {
public class ImageSource: global::Compatlib.System.Windows.DependencyObject {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageSource: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageSource: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageSource]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageSource]

} // end of class: ImageSource

} // end of namespace: Compatlib.System.Windows.Media
