// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Media {
public class ImageBrush: global::Compatlib.System.Windows.Media.TileBrush {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void <init>()]
    base.brush = new global::System.Windows.Media.ImageBrush();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void <init>()]
}

public virtual void setImageSource(Compatlib.System.Windows.Media.Imaging.BitmapImage n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void setImageSource(Compatlib.System.Windows.Media.Imaging.BitmapImage)]
    ((global::System.Windows.Media.ImageBrush)base.brush).ImageSource = n1.bitmapImage;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void setImageSource(Compatlib.System.Windows.Media.Imaging.BitmapImage)]
}

public virtual void setStretch(Compatlib.System.Windows.Media.Stretch n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void setStretch(Compatlib.System.Windows.Media.Stretch)]
    ((global::System.Windows.Media.ImageBrush)base.brush).Stretch = n1.stretch;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageBrush: void setStretch(Compatlib.System.Windows.Media.Stretch)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.ImageBrush]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.ImageBrush]

} // end of class: ImageBrush

} // end of namespace: Compatlib.System.Windows.Media
