// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Media {
public class Stretch: global::java.lang.Object {

static Stretch() {
    @static();
}

public static Compatlib.System.Windows.Media.Stretch _fFill;

public static Compatlib.System.Windows.Media.Stretch _fUniform;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Stretch: void <clinit>()]
    _fFill = new Stretch();
    _fFill.stretch = global::System.Windows.Media.Stretch.Fill;

    _fUniform = new Stretch();
    _fUniform.stretch = global::System.Windows.Media.Stretch.Uniform;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Stretch: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Stretch: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Stretch: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Stretch]
public global::System.Windows.Media.Stretch stretch;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Stretch]

} // end of class: Stretch

} // end of namespace: Compatlib.System.Windows.Media
