// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Input {
public class TouchAction: global::Compatlib.System.Object {

static TouchAction() {
    @static();
}

public static global::Compatlib.System.Windows.Input.TouchAction _fDown;

public static global::Compatlib.System.Windows.Input.TouchAction _fUp;

public static global::Compatlib.System.Windows.Input.TouchAction _fMove;

public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <init>()]
}

public static void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <clinit>()]
    _fDown = new TouchAction();
    _fUp = new TouchAction();
    _fMove = new TouchAction();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchAction]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchAction]

} // end of class: TouchAction

} // end of namespace: Compatlib.System.Windows.Input
