// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Input {
public class Touch: global::Compatlib.System.Object {

static Touch() {
    @static();
}

public static global::Compatlib.System.Windows.Input.FrameReportedEvent _fFrameReported;

public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch: void <init>()]
}

public static void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch: void <clinit>()]
    _fFrameReported = new FrameReportedEvent();
    _fFrameReported.@this();

    global::System.Windows.Input.Touch.FrameReported += FrameReportedHandler;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.Touch]
static void FrameReportedHandler(object sender, global::System.Windows.Input.TouchFrameEventArgs args)
{
    Compatlib.System.Windows.Input.TouchFrameEventArgs newArgs = new Compatlib.System.Windows.Input.TouchFrameEventArgs();
    newArgs.args = args;
    _fFrameReported._1_1fire(null, newArgs);
}
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.Touch]

} // end of class: Touch

} // end of namespace: Compatlib.System.Windows.Input
