// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Input {
public class TouchFrameEventArgs: global::Compatlib.System.EventArgs {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs: void <init>()]
}

public virtual global::System.Object GetPrimaryTouchPoint(global::Compatlib.System.Windows.UIElement n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs: Compatlib.System.Windows.Input.TouchPoint GetPrimaryTouchPoint(Compatlib.System.Windows.UIElement)]
    TouchPoint point = new TouchPoint();
    point.touchPoint = args.GetPrimaryTouchPoint(n1 != null ? n1.element : null);
    return point;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs: Compatlib.System.Windows.Input.TouchPoint GetPrimaryTouchPoint(Compatlib.System.Windows.UIElement)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs]
public global::System.Windows.Input.TouchFrameEventArgs args;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Input.TouchFrameEventArgs]

} // end of class: TouchFrameEventArgs

} // end of namespace: Compatlib.System.Windows.Input
