#!/bin/bash

# find XMLVMHOME
pushd >/dev/null `dirname $0`
cd ../..
export XMLVMHOME=`pwd`
popd >/dev/null

PLUGINS=var/tools/projectcheck.d

export ANDROID_PROJECTS="afireworks aremote helloworld sayhello xokoban"
export IPHONE_PROJECTS="gl/nehelesson4 ifireworks ihelloworld/fullscreen ihelloworld/landscape ihelloworld/portrait ihelloworld/upsidedown iremote isound navigation"


# Execute all plugins
for i in `ls "$XMLVMHOME/$PLUGINS"` ; do
	cd "$XMLVMHOME"
	bash "$XMLVMHOME/$PLUGINS/$i"
	if [ "$?" != 0 ] ; then
		echo "Error while executing $i"
		exit 1
	fi
done

