#!/bin/bash

# find XMLVMHOME
pushd >/dev/null `dirname $0`
cd ../..
export XMLVMHOME=`pwd`
popd >/dev/null

PLUGINS=var/tools/projectcheck.d

export ANDROID_PROJECTS="afireworks aremote helloworld sayhello xokoban"
export IPHONE_PROJECTS="gl/nehelesson4 ifireworks ihelloworld/fullscreen ihelloworld/landscape ihelloworld/portrait ihelloworld/upsidedown iremote isound navigation"

# Useful functions
function ask () {
    echo -n "$1 [Y/n] "
    local __FULL
    read __FULL
	if [ -z "$__FULL" ] ; then return 0; fi
    return `expr $__FULL : [^yY]`
}
export -f ask

# Execute all plugins
for i in `ls "$XMLVMHOME/$PLUGINS"` ; do
	cd "$XMLVMHOME"
	NAME=`echo $i | sed -e 's/^[0123456789]*-//g' | sed -e 's/_/ /g'`
	if ask "Do you want to perform '$NAME'?" ; then
		echo "Executing '$NAME'"
		bash "$XMLVMHOME/$PLUGINS/$i"
		if [ "$?" != 0 ] ; then
			echo "Error while executing $i"
			exit 1
		fi
	fi
done

