// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.io {
public class FileDescriptor: global::java.lang.Object {
private static void oneTimeInitialization(){
//XMLVM_BEGIN_WRAPPER[java.io.FileDescriptor: void oneTimeInitialization()]
      //Do nothing
//XMLVM_END_WRAPPER[java.io.FileDescriptor: void oneTimeInitialization()]
}

private void syncImpl(){
//XMLVM_BEGIN_WRAPPER[java.io.FileDescriptor: void syncImpl()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.FileDescriptor: void syncImpl()]
}

//XMLVM_BEGIN_WRAPPER[java.io.FileDescriptor]
//XMLVM_END_WRAPPER[java.io.FileDescriptor]

} // end of class: FileDescriptor

} // end of namespace: java.io
