// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.io {
public class File: global::java.lang.Object,global::java.io.Serializable,global::java.lang.Comparable {
private static void oneTimeInitialization(){
//XMLVM_BEGIN_WRAPPER[java.io.File: void oneTimeInitialization()]
      //Do nothing
//XMLVM_END_WRAPPER[java.io.File: void oneTimeInitialization()]
}

private static global::System.Object rootsImpl(){
//XMLVM_BEGIN_WRAPPER[java.io.File: byte[][] rootsImpl()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: byte[][] rootsImpl()]
}

private static bool isCaseSensitiveImpl(){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isCaseSensitiveImpl()]
      return true;
//XMLVM_END_WRAPPER[java.io.File: boolean isCaseSensitiveImpl()]
}

private bool deleteDirImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean deleteDirImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean deleteDirImpl(byte[])]
}

private bool deleteFileImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean deleteFileImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean deleteFileImpl(byte[])]
}

private bool existsImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean existsImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean existsImpl(byte[])]
}

private global::System.Object getCanonImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: byte[] getCanonImpl(byte[])]
      return n1;
//XMLVM_END_WRAPPER[java.io.File: byte[] getCanonImpl(byte[])]
}

private long getTotalSpaceImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: long getTotalSpaceImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: long getTotalSpaceImpl(byte[])]
}

private long getUsableSpaceImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: long getUsableSpaceImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: long getUsableSpaceImpl(byte[])]
}

private long getFreeSpaceImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: long getFreeSpaceImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: long getFreeSpaceImpl(byte[])]
}

private bool isDirectoryImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isDirectoryImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isDirectoryImpl(byte[])]
}

private bool isFileImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isFileImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isFileImpl(byte[])]
}

private bool isHiddenImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isHiddenImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isHiddenImpl(byte[])]
}

private bool isReadOnlyImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isReadOnlyImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isReadOnlyImpl(byte[])]
}

private bool isWriteOnlyImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isWriteOnlyImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isWriteOnlyImpl(byte[])]
}

private global::System.Object getLinkImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: byte[] getLinkImpl(byte[])]
      return n1;
//XMLVM_END_WRAPPER[java.io.File: byte[] getLinkImpl(byte[])]
}

private long lastModifiedImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: long lastModifiedImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: long lastModifiedImpl(byte[])]
}

private bool setLastModifiedImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, long n2){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean setLastModifiedImpl(byte[], long)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean setLastModifiedImpl(byte[], long)]
}

private bool setReadOnlyImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean setReadOnlyImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean setReadOnlyImpl(byte[])]
}

private bool setReadableImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, bool n3){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean setReadableImpl(byte[], boolean, boolean)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean setReadableImpl(byte[], boolean, boolean)]
}

private bool setWritableImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, bool n3){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean setWritableImpl(byte[], boolean, boolean)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean setWritableImpl(byte[], boolean, boolean)]
}

private long lengthImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: long lengthImpl(byte[])]
#if CONSOLE
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#else 
    if (this.info == null)
    {
        initNativeFileInfo(n1);
    }
    global::System.Diagnostics.Debug.WriteLine(info.Stream.Length);
    return info.Stream.Length;
#endif
//XMLVM_END_WRAPPER[java.io.File: long lengthImpl(byte[])]
}

private static global::System.Object listImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: byte[][] listImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: byte[][] listImpl(byte[])]
}

private bool mkdirImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean mkdirImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean mkdirImpl(byte[])]
}

private int newFileImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: int newFileImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: int newFileImpl(byte[])]
}

private bool renameToImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean renameToImpl(byte[], byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean renameToImpl(byte[], byte[])]
}

private bool setExecutableImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, bool n3){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean setExecutableImpl(byte[], boolean, boolean)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean setExecutableImpl(byte[], boolean, boolean)]
}

private bool isExecutableImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.io.File: boolean isExecutableImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.File: boolean isExecutableImpl(byte[])]
}

//XMLVM_BEGIN_WRAPPER[java.io.File]
#if CONSOLE

#else 
private global::System.Windows.Resources.StreamResourceInfo info;

private void initNativeFileInfo(global::org.xmlvm._nArrayAdapter<sbyte> n1)
{
    global::java.lang.String str = new global::java.lang.String();
    str.@this(n1);
    string nativeStr = global::org.xmlvm._nUtil.toNativeString(str);
    if(nativeStr.StartsWith("/")) {
        nativeStr = nativeStr.Substring(1);
    }
    global::System.Uri uri = new global::System.Uri(nativeStr, global::System.UriKind.Relative);
    info = global::System.Windows.Application.GetResourceStream(uri);
}
#endif
//XMLVM_END_WRAPPER[java.io.File]

} // end of class: File

} // end of namespace: java.io
