// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.io {
public class ObjectStreamClass: java.lang.Object,java.io.Serializable {
private static void oneTimeInitialization(){
//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass: void oneTimeInitialization()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass: void oneTimeInitialization()]
}

public static global::System.Object getConstructorSignature(java.lang.reflect.Constructor n1){
//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass: java.lang.String getConstructorSignature(java.lang.reflect.Constructor)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass: java.lang.String getConstructorSignature(java.lang.reflect.Constructor)]
}

private static global::System.Object getFieldSignature(java.lang.reflect.Field n1){
//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass: java.lang.String getFieldSignature(java.lang.reflect.Field)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass: java.lang.String getFieldSignature(java.lang.reflect.Field)]
}

public static global::System.Object getMethodSignature(java.lang.reflect.Method n1){
//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass: java.lang.String getMethodSignature(java.lang.reflect.Method)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass: java.lang.String getMethodSignature(java.lang.reflect.Method)]
}

private static bool hasClinit(java.lang.Class n1){
//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass: boolean hasClinit(java.lang.Class)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass: boolean hasClinit(java.lang.Class)]
}

//XMLVM_BEGIN_WRAPPER[java.io.ObjectStreamClass]
//XMLVM_END_WRAPPER[java.io.ObjectStreamClass]

} // end of class: ObjectStreamClass

} // end of namespace: java.io
