
#include "xmlvm.h"
#include "org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder.h"


//XMLVM_BEGIN_NATIVE_IMPLEMENTATION
//XMLVM_END_NATIVE_IMPLEMENTATION

void org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder_nDecode___char_1ARRAY_int_int_long_int_int_1ARRAY(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_INT n2, JAVA_INT n3, JAVA_LONG n4, JAVA_INT n5, JAVA_OBJECT n6)
{
    //XMLVM_BEGIN_NATIVE[org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder_nDecode___char_1ARRAY_int_int_long_int_int_1ARRAY]
    XMLVM_UNIMPLEMENTED_NATIVE_METHOD();
    //XMLVM_END_NATIVE
}


void xmlvm_init_native_org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder()
{
#ifdef XMLVM_VTABLE_IDX_org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder_nDecode___char_1ARRAY_int_int_long_int_int_1ARRAY
    __TIB_org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder.vtable[XMLVM_VTABLE_IDX_org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder_nDecode___char_1ARRAY_int_int_long_int_int_1ARRAY] = 
        (VTABLE_PTR) org_apache_harmony_niochar_charset_additional_x_MS950_HKSCS_Decoder_nDecode___char_1ARRAY_int_int_long_int_int_1ARRAY;
#endif
}
