// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace org.apache.harmony.luni.platform {
public class OSMemory: global::java.lang.Object,global::org.apache.harmony.luni.platform.IMemorySystem {

private static bool isLittleEndianImpl(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSMemory: boolean isLittleEndianImpl()]
    return global::System.BitConverter.IsLittleEndian;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSMemory: boolean isLittleEndianImpl()]
}

private static int getPointerSizeImpl(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSMemory: int getPointerSizeImpl()]
    return 4;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSMemory: int getPointerSizeImpl()]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSMemory]
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSMemory]

} // end of class: OSMemory

} // end of namespace: org.apache.harmony.luni.platform
