// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Collections.Generics {
public abstract class _iICollection {

} // end of abstract class: _iICollection

public interface ICollection {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.ICollection]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.ICollection]

} // end of interface: ICollection

} // end of namespace: Compatlib.System.Collections.Generics
