// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Collections.Generics {
public abstract class _iIDictionary {

} // end of abstract class: _iIDictionary

public interface IDictionary {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IDictionary]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IDictionary]

} // end of interface: IDictionary

} // end of namespace: Compatlib.System.Collections.Generics
