// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Collections.Generics {
public abstract class _iIEnumerable {

} // end of abstract class: _iIEnumerable

public interface IEnumerable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IEnumerable]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IEnumerable]

} // end of interface: IEnumerable

} // end of namespace: Compatlib.System.Collections.Generics
