// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Collections.Generics {
public abstract class _iIEnumerator: Compatlib.System.IDisposable {

} // end of abstract class: _iIEnumerator

public interface IEnumerator: Compatlib.System.IDisposable {
 global::System.Object getCurrent();

 bool MoveNext();

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IEnumerator]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IEnumerator]

} // end of interface: IEnumerator

} // end of namespace: Compatlib.System.Collections.Generics
