// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Collections.Generics {
public abstract class _iIList {

} // end of abstract class: _iIList

public interface IList {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.IList]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.IList]

} // end of interface: IList

} // end of namespace: Compatlib.System.Collections.Generics
