// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Collections.Generics {
public class List: global::Compatlib.System.Object,Compatlib.System.Collections.Generics.IList,Compatlib.System.Collections.Generics.ICollection,Compatlib.System.Collections.Generics.IEnumerable {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.List: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.List: void <init>()]
}

public virtual global::System.Object _1_1access(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.List: java.lang.Object __access(int)]
    return list[n1];
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.List: java.lang.Object __access(int)]
}

public virtual int getCount(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.List: int getCount()]
return list.Count;
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.List: int getCount()]
}

public virtual void Add(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.List: void Add(java.lang.Object)]
list.Add(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.List: void Add(java.lang.Object)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Collections.Generics.List]
private global::System.Collections.Generic.List<java.lang.Object> list = new global::System.Collections.Generic.List<java.lang.Object>();
//XMLVM_END_WRAPPER[Compatlib.System.Collections.Generics.List]

} // end of class: List

} // end of namespace: Compatlib.System.Collections.Generics
