// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Media.Imaging {
public class BitmapSource: global::Compatlib.System.Windows.Media.ImageSource {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: void <init>()]
}

public virtual int getPixelWidth(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: int getPixelWidth()]
    if (this is global::Compatlib.System.Windows.Media.Imaging.BitmapImage)
    {
        return ((global::Compatlib.System.Windows.Media.Imaging.BitmapImage)this).bitmapImage.PixelWidth;
    }
    else
    {
        throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
    }
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: int getPixelWidth()]
}

public virtual int getPixelHeight(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: int getPixelHeight()]
    if (this is global::Compatlib.System.Windows.Media.Imaging.BitmapImage)
    {
        return ((global::Compatlib.System.Windows.Media.Imaging.BitmapImage)this).bitmapImage.PixelHeight;
    }
    else
    {
        throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
    }
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource: int getPixelHeight()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapSource]

} // end of class: BitmapSource

} // end of namespace: Compatlib.System.Windows.Media.Imaging
