// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Media.Imaging {
public class BitmapImage: global::Compatlib.System.Windows.Media.Imaging.BitmapSource {
public void @this(global::Compatlib.System.Uri n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapImage: void <init>(Compatlib.System.Uri)]
    bitmapImage = new global::System.Windows.Media.Imaging.BitmapImage(n1.uri);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapImage: void <init>(Compatlib.System.Uri)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapImage]
public global::System.Windows.Media.Imaging.BitmapImage bitmapImage;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Media.Imaging.BitmapImage]

} // end of class: BitmapImage

} // end of namespace: Compatlib.System.Windows.Media.Imaging
