// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.lang {
public class Object {
private static void initNativeLayer(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void initNativeLayer()]
    // nothing to do here
//XMLVM_END_WRAPPER[java.lang.Object: void initNativeLayer()]
}

public virtual global::System.Object clone(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: java.lang.Object clone()]
      return base.MemberwiseClone();
//XMLVM_END_WRAPPER[java.lang.Object: java.lang.Object clone()]
}

public virtual bool equals(java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: boolean equals(java.lang.Object)]
      return this.Equals(n1);
//XMLVM_END_WRAPPER[java.lang.Object: boolean equals(java.lang.Object)]
}

public virtual void @finally(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void finalize()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void finalize()]
}

public virtual global::System.Object getClass(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: java.lang.Class getClass()]
    global::System.Type myType = this.GetType();
    //org.xmlvm._nTIB myTIB = org.xmlvm._nTIB.getTIB(myType);
    java.lang.Class myClass = org.xmlvm._nTIB.getClass(myType);
    return myClass;
//XMLVM_END_WRAPPER[java.lang.Object: java.lang.Class getClass()]
}

public virtual int hashCode(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: int hashCode()]
    // in the meantime we return the native hash:
    return this.GetHashCode();
//XMLVM_END_WRAPPER[java.lang.Object: int hashCode()]
}

public virtual void notify(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void notify()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void notify()]
}

public virtual void notifyAll(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void notifyAll()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void notifyAll()]
}

public virtual global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: java.lang.String toString()]
    java.lang.Class myClass = (java.lang.Class) this.getClass();
    java.lang.String myClassName = (java.lang.String) myClass.getName();
    string nativeStr = org.xmlvm._nUtil.toNativeString(myClassName);
    nativeStr = nativeStr + "@";
    int myHash = this.hashCode();
    java.lang.String myHashString = (java.lang.String) java.lang.Integer.toHexString(myHash);
    nativeStr = nativeStr + org.xmlvm._nUtil.toNativeString(myHashString);
    java.lang.String result = org.xmlvm._nUtil.toJavaString(nativeStr);
    return result;
//XMLVM_END_WRAPPER[java.lang.Object: java.lang.String toString()]
}

public virtual void wait(){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void wait()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void wait()]
}

public virtual void wait(long n1){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void wait(long)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void wait(long)]
}

public virtual void wait(long n1, int n2){
//XMLVM_BEGIN_WRAPPER[java.lang.Object: void wait(long, int)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.Object: void wait(long, int)]
}

//XMLVM_BEGIN_WRAPPER[java.lang.Object]
//XMLVM_END_WRAPPER[java.lang.Object]

} // end of class: Object

} // end of namespace: java.lang
