// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.lang {
public class Void: global::java.lang.Object {
private static void initVoid(){
//XMLVM_BEGIN_WRAPPER[java.lang.Void: void initVoid()]
//XMLVM_END_WRAPPER[java.lang.Void: void initVoid()]
}

//XMLVM_BEGIN_WRAPPER[java.lang.Void]
//XMLVM_END_WRAPPER[java.lang.Void]

} // end of class: Void

} // end of namespace: java.lang
