// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace org.xmlvm.runtime {
public class XMLVMArray: java.lang.Object,java.lang.Cloneable,java.io.Serializable {
private static void initNativeLayer(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: void initNativeLayer()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: void initNativeLayer()]
}

private static global::System.Object createSingleDimension(java.lang.Class n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createSingleDimension(java.lang.Class, int)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createSingleDimension(java.lang.Class, int)]
}

private static global::System.Object createSingleDimensionWithData(java.lang.Class n1, int n2, java.lang.Object n3){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createSingleDimensionWithData(java.lang.Class, int, java.lang.Object)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createSingleDimensionWithData(java.lang.Class, int, java.lang.Object)]
}

private static global::System.Object createMultiDimensions(java.lang.Class n1, org.xmlvm.runtime.XMLVMArray n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createMultiDimensions(java.lang.Class, org.xmlvm.runtime.XMLVMArray)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: org.xmlvm.runtime.XMLVMArray createMultiDimensions(java.lang.Class, org.xmlvm.runtime.XMLVMArray)]
}

private static void fillArray(org.xmlvm.runtime.XMLVMArray n1, java.lang.Object n2){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: void fillArray(org.xmlvm.runtime.XMLVMArray, java.lang.Object)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: void fillArray(org.xmlvm.runtime.XMLVMArray, java.lang.Object)]
}

public override global::System.Object clone(){
//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray: java.lang.Object clone()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray: java.lang.Object clone()]
}

//XMLVM_BEGIN_WRAPPER[org.xmlvm.runtime.XMLVMArray]
//XMLVM_END_WRAPPER[org.xmlvm.runtime.XMLVMArray]

} // end of class: XMLVMArray

} // end of namespace: org.xmlvm.runtime
