// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Controls.Primitives {
public class ToggleButton: global::Compatlib.System.Windows.Controls.Primitives.ButtonBase {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: void <init>()]
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: void <init>()]
}

public virtual void setIsChecked(bool n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: void setIsChecked(boolean)]
    ((global::System.Windows.Controls.Primitives.ToggleButton)base.element).IsChecked = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: void setIsChecked(boolean)]
}

public virtual global::System.Object getIsChecked(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: Compatlib.System.Boolean getIsChecked()]
    Compatlib.System.Boolean ret = new Compatlib.System.Boolean();
    ret.boolean = ((global::System.Windows.Controls.Primitives.ToggleButton)base.element).IsChecked.Value;
    return ret;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton: Compatlib.System.Boolean getIsChecked()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Primitives.ToggleButton]

} // end of class: ToggleButton

} // end of namespace: Compatlib.System.Windows.Controls.Primitives
