// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace sun.misc {
public class Unsafe: global::java.lang.Object {
public virtual long objectFieldOffset(global::java.lang.reflect.Field n1){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: long objectFieldOffset(java.lang.reflect.Field)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: long objectFieldOffset(java.lang.reflect.Field)]
}

public virtual bool compareAndSwapInt(global::java.lang.Object n1, long n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapInt(java.lang.Object, long, int, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapInt(java.lang.Object, long, int, int)]
}

public virtual bool compareAndSwapLong(global::java.lang.Object n1, long n2, long n3, long n4){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapLong(java.lang.Object, long, long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapLong(java.lang.Object, long, long, long)]
}

public virtual bool compareAndSwapObject(global::java.lang.Object n1, long n2, global::java.lang.Object n3, global::java.lang.Object n4){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapObject(java.lang.Object, long, java.lang.Object, java.lang.Object)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: boolean compareAndSwapObject(java.lang.Object, long, java.lang.Object, java.lang.Object)]
}

public virtual int arrayBaseOffset(global::java.lang.Class n1){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: int arrayBaseOffset(java.lang.Class)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: int arrayBaseOffset(java.lang.Class)]
}

public virtual int arrayIndexScale(global::java.lang.Class n1){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: int arrayIndexScale(java.lang.Class)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: int arrayIndexScale(java.lang.Class)]
}

public virtual void putIntVolatile(global::java.lang.Object n1, long n2, int n3){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void putIntVolatile(java.lang.Object, long, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void putIntVolatile(java.lang.Object, long, int)]
}

public virtual int getIntVolatile(global::java.lang.Object n1, long n2){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: int getIntVolatile(java.lang.Object, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: int getIntVolatile(java.lang.Object, long)]
}

public virtual void putLongVolatile(global::java.lang.Object n1, long n2, long n3){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void putLongVolatile(java.lang.Object, long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void putLongVolatile(java.lang.Object, long, long)]
}

public virtual long getLongVolatile(global::java.lang.Object n1, long n2){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: long getLongVolatile(java.lang.Object, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: long getLongVolatile(java.lang.Object, long)]
}

public virtual void putObjectVolatile(global::java.lang.Object n1, long n2, global::java.lang.Object n3){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void putObjectVolatile(java.lang.Object, long, java.lang.Object)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void putObjectVolatile(java.lang.Object, long, java.lang.Object)]
}

public virtual global::System.Object getObjectVolatile(global::java.lang.Object n1, long n2){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: java.lang.Object getObjectVolatile(java.lang.Object, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: java.lang.Object getObjectVolatile(java.lang.Object, long)]
}

public virtual void putLong(global::java.lang.Object n1, long n2, long n3){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void putLong(java.lang.Object, long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void putLong(java.lang.Object, long, long)]
}

public virtual long getLong(global::java.lang.Object n1, long n2){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: long getLong(java.lang.Object, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: long getLong(java.lang.Object, long)]
}

public virtual void unpark(global::java.lang.Thread n1){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void unpark(java.lang.Thread)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void unpark(java.lang.Thread)]
}

public virtual void park(bool n1, long n2){
//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe: void park(boolean, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[sun.misc.Unsafe: void park(boolean, long)]
}

//XMLVM_BEGIN_WRAPPER[sun.misc.Unsafe]
//XMLVM_END_WRAPPER[sun.misc.Unsafe]

} // end of class: Unsafe

} // end of namespace: sun.misc
