// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace org.apache.harmony.niochar.charset {
public class US_1ASCII_2Decoder: global::java.nio.charset.CharsetDecoder {
private int nDecode(global::org.xmlvm._nArrayAdapter<char> n1, int n2, int n3, long n4, int n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.US_ASCII$Decoder: int nDecode(char[], int, int, long, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.US_ASCII$Decoder: int nDecode(char[], int, int, long, int)]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.US_ASCII$Decoder]
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.US_ASCII$Decoder]

} // end of class: US_1ASCII_2Decoder

} // end of namespace: org.apache.harmony.niochar.charset
