// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class Locale: java.lang.Object,java.lang.Cloneable,java.io.Serializable {
private static void initNativeLayer(){
//XMLVM_BEGIN_WRAPPER[java.util.Locale: void initNativeLayer()]
    global::java.util.Locale._fENGLISH = new global::java.util.Locale();
    global::java.util.Locale._fENGLISH.@this(global::org.xmlvm._nUtil.toJavaString("en"), global::org.xmlvm._nUtil.toJavaString(""));
    setDefault(_fENGLISH);
//XMLVM_END_WRAPPER[java.util.Locale: void initNativeLayer()]
}

//XMLVM_BEGIN_WRAPPER[java.util.Locale]
//XMLVM_END_WRAPPER[java.util.Locale]

} // end of class: Locale

} // end of namespace: java.util
