// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util {
public class Properties: global::java.util.Hashtable {
public void @this(){
//XMLVM_BEGIN_WRAPPER[java.util.Properties: void <init>()]
    org.xmlvm._nElement _r0;
    _r0.i = 0;
    _r0.l = 0;
    _r0.f = 0;
    _r0.d = 0;
    global::System.Object _r0_o = null;
    org.xmlvm._nElement _r1;
    _r1.i = 0;
    _r1.l = 0;
    _r1.f = 0;
    _r1.d = 0;
    global::System.Object _r1_o = null;
    org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    ((java.util.Hashtable) _r1_o).@this();
    _r0_o = null;
    return;
//XMLVM_END_WRAPPER[java.util.Properties: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[java.util.Properties]
//XMLVM_END_WRAPPER[java.util.Properties]

} // end of class: Properties

} // end of namespace: java.util
