// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public abstract class TimeZone: java.lang.Object,java.io.Serializable,java.lang.Cloneable {
private static global::System.Object getCustomTimeZone(org.xmlvm._nArrayAdapter<int> n1, org.xmlvm._nArrayAdapter<bool> n2){
//XMLVM_BEGIN_WRAPPER[java.util.TimeZone: java.lang.String getCustomTimeZone(int[], boolean[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.TimeZone: java.lang.String getCustomTimeZone(int[], boolean[])]
}

//XMLVM_BEGIN_WRAPPER[java.util.TimeZone]
//XMLVM_END_WRAPPER[java.util.TimeZone]

} // end of class: TimeZone

} // end of namespace: java.util
