// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Threading {
public class Thread: global::Compatlib.System.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Threading.Thread: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Threading.Thread: void <init>()]
}

public static void Sleep(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Threading.Thread: void Sleep(int)]
    global::System.Threading.Thread.Sleep(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Threading.Thread: void Sleep(int)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Threading.Thread]
//XMLVM_END_WRAPPER[Compatlib.System.Threading.Thread]

} // end of class: Thread

} // end of namespace: Compatlib.System.Threading
