
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
MIDIThruConnectionEndpoint toMIDIThruConnectionEndpoint(void * obj);
JAVA_OBJECT fromMIDIThruConnectionEndpoint(MIDIThruConnectionEndpoint obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_MIDIThruConnectionEndpoint
//XMLVM_END_DECLARATIONS