
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
SCNetworkConnectionContext toSCNetworkConnectionContext(void * obj);
JAVA_OBJECT fromSCNetworkConnectionContext(SCNetworkConnectionContext obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_SCNetworkConnectionContext
//XMLVM_END_DECLARATIONS