
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioStreamBasicDescription toAudioStreamBasicDescription(void * obj);
JAVA_OBJECT fromAudioStreamBasicDescription(AudioStreamBasicDescription obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioStreamBasicDescription
//XMLVM_END_DECLARATIONS