
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
SCNetworkReachabilityContext toSCNetworkReachabilityContext(void * obj);
JAVA_OBJECT fromSCNetworkReachabilityContext(SCNetworkReachabilityContext obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_SCNetworkReachabilityContext
//XMLVM_END_DECLARATIONS