
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioStreamPacketDescription toAudioStreamPacketDescription(void * obj);
JAVA_OBJECT fromAudioStreamPacketDescription(AudioStreamPacketDescription obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioStreamPacketDescription
//XMLVM_END_DECLARATIONS