
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
SMPTETime toSMPTETime(void * obj);
JAVA_OBJECT fromSMPTETime(SMPTETime obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_SMPTETime
//XMLVM_END_DECLARATIONS