
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
CVSMPTETime toCVSMPTETime(void * obj);
JAVA_OBJECT fromCVSMPTETime(CVSMPTETime obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_CVSMPTETime
//XMLVM_END_DECLARATIONS