
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
CGDataProviderSequentialCallbacks toCGDataProviderSequentialCallbacks(void * obj);
JAVA_OBJECT fromCGDataProviderSequentialCallbacks(CGDataProviderSequentialCallbacks obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_CGDataProviderSequentialCallbacks
//XMLVM_END_DECLARATIONS