
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioUnitParameterValueFromString toAudioUnitParameterValueFromString(void * obj);
JAVA_OBJECT fromAudioUnitParameterValueFromString(AudioUnitParameterValueFromString obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioUnitParameterValueFromString
//XMLVM_END_DECLARATIONS