
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioUnitFrequencyResponseBin toAudioUnitFrequencyResponseBin(void * obj);
JAVA_OBJECT fromAudioUnitFrequencyResponseBin(AudioUnitFrequencyResponseBin obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioUnitFrequencyResponseBin
//XMLVM_END_DECLARATIONS