
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioUnitParameterHistoryInfo toAudioUnitParameterHistoryInfo(void * obj);
JAVA_OBJECT fromAudioUnitParameterHistoryInfo(AudioUnitParameterHistoryInfo obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioUnitParameterHistoryInfo
//XMLVM_END_DECLARATIONS