
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
CVPlanarPixelBufferInfo_YCbCrBiPlanar toCVPlanarPixelBufferInfo_YCbCrBiPlanar(void * obj);
JAVA_OBJECT fromCVPlanarPixelBufferInfo_YCbCrBiPlanar(CVPlanarPixelBufferInfo_YCbCrBiPlanar obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_CVPlanarPixelBufferInfo_YCbCrBiPlanar
//XMLVM_END_DECLARATIONS