
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AUInputSamplesInOutputCallbackStruct toAUInputSamplesInOutputCallbackStruct(void * obj);
JAVA_OBJECT fromAUInputSamplesInOutputCallbackStruct(AUInputSamplesInOutputCallbackStruct obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AUInputSamplesInOutputCallbackStruct
//XMLVM_END_DECLARATIONS