
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
MIDIObjectPropertyChangeNotification toMIDIObjectPropertyChangeNotification(void * obj);
JAVA_OBJECT fromMIDIObjectPropertyChangeNotification(MIDIObjectPropertyChangeNotification obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_MIDIObjectPropertyChangeNotification
//XMLVM_END_DECLARATIONS