
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
CGDataProviderDirectCallbacks toCGDataProviderDirectCallbacks(void * obj);
JAVA_OBJECT fromCGDataProviderDirectCallbacks(CGDataProviderDirectCallbacks obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_CGDataProviderDirectCallbacks
//XMLVM_END_DECLARATIONS