
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AUMIDIOutputCallbackStruct toAUMIDIOutputCallbackStruct(void * obj);
JAVA_OBJECT fromAUMIDIOutputCallbackStruct(AUMIDIOutputCallbackStruct obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AUMIDIOutputCallbackStruct
//XMLVM_END_DECLARATIONS