
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioUnitParameterValueName toAudioUnitParameterValueName(void * obj);
JAVA_OBJECT fromAudioUnitParameterValueName(AudioUnitParameterValueName obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioUnitParameterValueName
//XMLVM_END_DECLARATIONS