
//XMLVM_BEGIN_DECLARATIONS
#import <UIKit/UIKit.h>
AudioUnitMIDIControlMapping toAudioUnitMIDIControlMapping(void * obj);
JAVA_OBJECT fromAudioUnitMIDIControlMapping(AudioUnitMIDIControlMapping obj);
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_ios_AudioUnitMIDIControlMapping
//XMLVM_END_DECLARATIONS