// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System {
public class Delegate: global::java.lang.Object {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Delegate: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Delegate: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Delegate]
//XMLVM_END_WRAPPER[Compatlib.System.Delegate]

} // end of class: Delegate

} // end of namespace: Compatlib.System
