// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System {
public abstract class _iIFormattable {

} // end of abstract class: _iIFormattable

public interface IFormattable {
//XMLVM_BEGIN_WRAPPER[Compatlib.System.IFormattable]
//XMLVM_END_WRAPPER[Compatlib.System.IFormattable]

} // end of interface: IFormattable

} // end of namespace: Compatlib.System
