// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System {
public class Integer: global::Compatlib.System.Object {
public void @this(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Integer: void <init>(int)]
    integer = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Integer: void <init>(int)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Integer]
public global::System.Int32 integer;
//XMLVM_END_WRAPPER[Compatlib.System.Integer]

} // end of class: Integer

} // end of namespace: Compatlib.System
