// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System {
public class Random: global::Compatlib.System.Object {
public void @this(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Random: void <init>(int)]
    random = new global::System.Random(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Random: void <init>(int)]
}

public virtual double NextDouble(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Random: double NextDouble()]
    return random.NextDouble();
//XMLVM_END_WRAPPER[Compatlib.System.Random: double NextDouble()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Random]
private global::System.Random random;
//XMLVM_END_WRAPPER[Compatlib.System.Random]

} // end of class: Random

} // end of namespace: Compatlib.System
