<?php
  include("../header.html");
  include("../content_top.html") ;
?>
<h1>Overview</h1>

<table>
  <tr>
    <td>
      <img src="overview.jpg" style="float:right;width:330px; margin:0px 30px 10px 30px;" alt="XMLVM Overview Diagram"/>
      <p>
        The goal of XMLVM is to offer a flexible and extensible cross-compiler toolchain. Instead of cross-compiling on a source code level, XMLVM
        cross-compiles byte code instructions from Sun Microsystem's virtual machine and Microsoft's Common Language Runtime. The benefit of this
        approach is that byte code instructions are easier to cross-compile and the difficult parsing of a high-level programming language is left
        to a regular compiler. In XMLVM, byte code-based programs are represented as XML documents. This allows manipulation and translation
        of XMLVM-based programs using advanced XML technologies such as XSLT, XQuery, and XPath.
      </p>
      <p>
        XMLVM serves as an <a href="../toolchain">umbrella for several projects</a>. For all projects, a Java class file
        or a .NET executable is first <a href="../frontend">translated to an XML-document</a>.
        Based on the XML-document generated by the front-end, various transformations are possible. The first transformation
        <a href="../clr2jvm">cross-compiles from .NET to JVM byte code</a>. Another transformation enables Java or .NET applications to
        be <a href="../javascript">cross-compiled to JavaScript</a> so that they can run as
        AJAX applications in any browser. Yet another transformation allows to <a href="../iphone">cross-compile a Java program to
        Objective-C</a> to create a native iPhone application.
      </p>
      <p>
		    You can even <a href ="../android">cross compile an Android application to run on the iPhone</a> <span class="new">New!</span>
      </p>
      
      <h2 style="margin-top:20px">Get involved <span class="new">New!</span></h2><br/>
      <table style="width:80%; margin-top: 5px; margin-left:auto; margin-right:auto; text-align:center; border:1px dashed gray;">
        <tr>
          <td style="vertical-align:middle;">
            <div class="rounded_rectangle"><a target="_blank" href="https://lists.sourceforge.net/lists/listinfo/xmlvm-users">xmlvm-users</a></div>
          </td>
          <td style="vertical-align:middle;">
            Get in contact with the developers and other users by subscribing to this mailing list.
          </td>
        </tr>
      </table>

    </td>
    <td>
      
    </td>
    <td style="border-left: 1px solid #AAA; width:150px; padding-left:10px;">
      <h4>What's new</h4>
      <div class="news_item">

<?php
  $doc = new DOMDocument();
  $doc->load('http://sourceforge.net/export/rss2_projnews.php?group_id=200328');
  $arrFeeds = array();
  $count = 0;
  foreach ($doc->getElementsByTagName('item') as $node) {
      # Set the maximum amount of new we want to show.
      if ($count++ >= 5) {
        break;
      }
      $title = $node->getElementsByTagName('title')->item(0)->nodeValue;
      $description = $node->getElementsByTagName('description')->item(0)->nodeValue;
      $date = $node->getElementsByTagName('pubDate')->item(0)->nodeValue;
      $date = date_parse($date);
      $dateStr = $date["day"]." ".date("M", mktime(0, 0, 0, $date["month"], 1, 2009))." ".$date["year"];
?>

        <div class="date"><?echo($dateStr);?></div>
        <h1><? echo($title);?></h1>
        <p><? echo($description);?></p>
<?php
 }
?>
      </div>
    </td>
  </tr>
</table>

<?php
  include("../footer.html");
?>
