// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.net {
public class InetAddress: global::java.lang.Object,global::java.io.Serializable {
private static void oneTimeInitialization(bool n1){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: void oneTimeInitialization(boolean)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: void oneTimeInitialization(boolean)]
}

public static global::System.Object getAliasesByNameImpl(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: java.net.InetAddress[] getAliasesByNameImpl(java.lang.String)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: java.net.InetAddress[] getAliasesByNameImpl(java.lang.String)]
}

public static global::System.Object getHostByAddrImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: java.net.InetAddress getHostByAddrImpl(byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: java.net.InetAddress getHostByAddrImpl(byte[])]
}

public static int inetAddrImpl(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: int inetAddrImpl(java.lang.String)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: int inetAddrImpl(java.lang.String)]
}

public static global::System.Object inetNtoaImpl(int n1){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: java.lang.String inetNtoaImpl(int)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: java.lang.String inetNtoaImpl(int)]
}

public static global::System.Object getHostByNameImpl(global::java.lang.String n1, bool n2){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: java.net.InetAddress getHostByNameImpl(java.lang.String, boolean)]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: java.net.InetAddress getHostByNameImpl(java.lang.String, boolean)]
}

public static global::System.Object getHostNameImpl(){
//XMLVM_BEGIN_WRAPPER[java.net.InetAddress: java.lang.String getHostNameImpl()]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.net.InetAddress: java.lang.String getHostNameImpl()]
}

//XMLVM_BEGIN_WRAPPER[java.net.InetAddress]
//XMLVM_END_WRAPPER[java.net.InetAddress]

} // end of class: InetAddress

} // end of namespace: java.net
