// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.lang.reflect {
public class Proxy: global::java.lang.Object,global::java.io.Serializable {
private static global::System.Object defineClassImpl(global::java.lang.ClassLoader n1, global::java.lang.String n2, global::org.xmlvm._nArrayAdapter<sbyte> n3){
//XMLVM_BEGIN_WRAPPER[java.lang.reflect.Proxy: java.lang.Class defineClassImpl(java.lang.ClassLoader, java.lang.String, byte[])]
      throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.lang.reflect.Proxy: java.lang.Class defineClassImpl(java.lang.ClassLoader, java.lang.String, byte[])]
}

//XMLVM_BEGIN_WRAPPER[java.lang.reflect.Proxy]
//XMLVM_END_WRAPPER[java.lang.reflect.Proxy]

} // end of class: Proxy

} // end of namespace: java.lang.reflect
