#ifndef __ORG_XMLVM_IPHONE_UIACCELEROMETERDELEGATE__
#define __ORG_XMLVM_IPHONE_UIACCELEROMETERDELEGATE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAccelerometer)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAcceleration
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAcceleration
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAcceleration)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIAccelerometerDelegate, 12)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate_ARRAYTYPE;

#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
typedef struct org_xmlvm_iphone_UIAccelerometerDelegate org_xmlvm_iphone_UIAccelerometerDelegate;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIAccelerometerDelegate 12
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIAccelerometerDelegate_accelerometerDidAccelerate___org_xmlvm_iphone_UIAccelerometer_org_xmlvm_iphone_UIAcceleration 11

void __INIT_FOR_CLASS_org_xmlvm_iphone_UIAccelerometerDelegate(__TIB_DEFINITION_TEMPLATE** interface);
void __INIT_org_xmlvm_iphone_UIAccelerometerDelegate();

#endif
