#ifndef __ORG_XMLVM_IPHONE_NSNOTIFICATIONDELEGATE__
#define __ORG_XMLVM_IPHONE_NSNOTIFICATIONDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotification
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotification
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNotification)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSNotificationDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationDelegate
typedef struct org_xmlvm_iphone_NSNotificationDelegate org_xmlvm_iphone_NSNotificationDelegate;
#endif

void __INIT_org_xmlvm_iphone_NSNotificationDelegate();
void __INIT_IMPL_org_xmlvm_iphone_NSNotificationDelegate();

#endif
