#ifndef __ORG_XMLVM_IPHONE_NSNETSERVICEBROWSERDELEGATE__
#define __ORG_XMLVM_IPHONE_NSNETSERVICEBROWSERDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSDictionary
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSDictionary
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSDictionary)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetService
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetService
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNetService)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowser
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowser
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNetServiceBrowser)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowserDelegate_Wrapper
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowserDelegate_Wrapper
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNetServiceBrowserDelegate_Wrapper)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSNetServiceBrowserDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNetServiceBrowserDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNetServiceBrowserDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNetServiceBrowserDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNetServiceBrowserDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowserDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNetServiceBrowserDelegate
typedef struct org_xmlvm_iphone_NSNetServiceBrowserDelegate org_xmlvm_iphone_NSNetServiceBrowserDelegate;
#endif

void __INIT_org_xmlvm_iphone_NSNetServiceBrowserDelegate();
void __INIT_IMPL_org_xmlvm_iphone_NSNetServiceBrowserDelegate();

#endif
