#ifndef __ORG_XMLVM_IPHONE_NSSTRINGCOMPAREOPTIONS__
#define __ORG_XMLVM_IPHONE_NSSTRINGCOMPAREOPTIONS__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
// Class declarations for org.xmlvm.iphone.NSStringCompareOptions
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSStringCompareOptions, 6, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_NSStringCompareOptions)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSStringCompareOptions;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSStringCompareOptions_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSStringCompareOptions_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSStringCompareOptions_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSStringCompareOptions
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_NSStringCompareOptions \
    __INSTANCE_FIELDS_java_lang_Object; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSStringCompareOptions \
    } org_xmlvm_iphone_NSStringCompareOptions

struct org_xmlvm_iphone_NSStringCompareOptions {
    __TIB_DEFINITION_org_xmlvm_iphone_NSStringCompareOptions* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_NSStringCompareOptions;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSStringCompareOptions
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSStringCompareOptions
typedef struct org_xmlvm_iphone_NSStringCompareOptions org_xmlvm_iphone_NSStringCompareOptions;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_NSStringCompareOptions 6

void __INIT_org_xmlvm_iphone_NSStringCompareOptions();
void __INIT_IMPL_org_xmlvm_iphone_NSStringCompareOptions();
void __DELETE_org_xmlvm_iphone_NSStringCompareOptions(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_NSStringCompareOptions(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_NSStringCompareOptions();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_NSStringCompareOptions();
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSCaseInsensitiveSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSCaseInsensitiveSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSLiteralSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSLiteralSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSBackwardsSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSBackwardsSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSAnchoredSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSAnchoredSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSNumericSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSNumericSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSDiacriticInsensitiveSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSDiacriticInsensitiveSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSWidthInsensitiveSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSWidthInsensitiveSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSForcedOrderingSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSForcedOrderingSearch(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSStringCompareOptions_GET_NSRegularExpressionSearch();
void org_xmlvm_iphone_NSStringCompareOptions_PUT_NSRegularExpressionSearch(JAVA_INT v);

// Define a Macro for the method declarations of the Obj-C wrapper class so that subclass wrappers may easily include these too
#define XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_NSStringCompareOptions \

// Define a Macro for the entire contents of the Obj-C wrapper class
#define XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_NSStringCompareOptions \


#endif
