#ifndef __ORG_XMLVM_IPHONE_UIBARBUTTONITEMDELEGATE__
#define __ORG_XMLVM_IPHONE_UIBARBUTTONITEMDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIBarButtonItemDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIBarButtonItemDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIBarButtonItemDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIBarButtonItemDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIBarButtonItemDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIBarButtonItemDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIBarButtonItemDelegate
typedef struct org_xmlvm_iphone_UIBarButtonItemDelegate org_xmlvm_iphone_UIBarButtonItemDelegate;
#endif

void __INIT_org_xmlvm_iphone_UIBarButtonItemDelegate();
void __INIT_IMPL_org_xmlvm_iphone_UIBarButtonItemDelegate();

#endif
