#ifndef __ORG_XMLVM_IPHONE_SKPAYMENTTRANSACTIONOBSERVER__
#define __ORG_XMLVM_IPHONE_SKPAYMENTTRANSACTIONOBSERVER__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "org_xmlvm_iphone_NSObject.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_util_List
#define XMLVM_FORWARD_DECL_java_util_List
XMLVM_FORWARD_DECL(java_util_List)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSError)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_SKPaymentQueue
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_SKPaymentQueue
XMLVM_FORWARD_DECL(org_xmlvm_iphone_SKPaymentQueue)
#endif
// Class declarations for org.xmlvm.iphone.SKPaymentTransactionObserver
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_SKPaymentTransactionObserver, 8, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_SKPaymentTransactionObserver)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_SKPaymentTransactionObserver;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_SKPaymentTransactionObserver_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_SKPaymentTransactionObserver_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_SKPaymentTransactionObserver_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_SKPaymentTransactionObserver
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_SKPaymentTransactionObserver \
    __INSTANCE_FIELDS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_SKPaymentTransactionObserver \
    } org_xmlvm_iphone_SKPaymentTransactionObserver

struct org_xmlvm_iphone_SKPaymentTransactionObserver {
    __TIB_DEFINITION_org_xmlvm_iphone_SKPaymentTransactionObserver* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_SKPaymentTransactionObserver;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_SKPaymentTransactionObserver
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_SKPaymentTransactionObserver
typedef struct org_xmlvm_iphone_SKPaymentTransactionObserver org_xmlvm_iphone_SKPaymentTransactionObserver;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_SKPaymentTransactionObserver 8
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_SKPaymentTransactionObserver_updatedTransactions___org_xmlvm_iphone_SKPaymentQueue_java_util_List 7

void __INIT_org_xmlvm_iphone_SKPaymentTransactionObserver();
void __INIT_IMPL_org_xmlvm_iphone_SKPaymentTransactionObserver();
void __DELETE_org_xmlvm_iphone_SKPaymentTransactionObserver(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_SKPaymentTransactionObserver(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_SKPaymentTransactionObserver();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_SKPaymentTransactionObserver();
void org_xmlvm_iphone_SKPaymentTransactionObserver___INIT___(JAVA_OBJECT me);
// Vtable index: 7
void org_xmlvm_iphone_SKPaymentTransactionObserver_updatedTransactions___org_xmlvm_iphone_SKPaymentQueue_java_util_List(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
void org_xmlvm_iphone_SKPaymentTransactionObserver_removedTransactions___org_xmlvm_iphone_SKPaymentQueue_java_util_List(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
void org_xmlvm_iphone_SKPaymentTransactionObserver_restoreCompletedTransactionsFailedWithError___org_xmlvm_iphone_SKPaymentQueue_org_xmlvm_iphone_NSError(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
void org_xmlvm_iphone_SKPaymentTransactionObserver_paymentQueueRestoreCompletedTransactionsFinished___org_xmlvm_iphone_SKPaymentQueue(JAVA_OBJECT me, JAVA_OBJECT n1);

// Define a Macro for the method declarations of the Obj-C wrapper class so that subclass wrappers may easily include these too
#define XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_SKPaymentTransactionObserver \
XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_NSObject \

// Define a Macro for the entire contents of the Obj-C wrapper class
#define XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_SKPaymentTransactionObserver \
XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_NSObject \


#endif
