#ifndef __ORG_XMLVM_IPHONE_UIPRINTINTERACTIONCONTROLLER__
#define __ORG_XMLVM_IPHONE_UIPRINTINTERACTIONCONTROLLER__

#include "xmlvm.h"
#include "org_xmlvm_iphone_NSObject.h"
#include "org_xmlvm_iphone_NSObject.h"

// Preprocessor constants for interfaces:

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIView
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIView
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIView)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIBarButtonItem
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIBarButtonItem
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIBarButtonItem)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSObject)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSData
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSData
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSData)
#endif
#ifndef XMLVM_FORWARD_DECL_java_util_ArrayList
#define XMLVM_FORWARD_DECL_java_util_ArrayList
XMLVM_FORWARD_DECL(java_util_ArrayList)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURL
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURL
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSURL)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSObject)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGRect
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGRect
XMLVM_FORWARD_DECL(org_xmlvm_iphone_CGRect)
#endif
// Class declarations for org.xmlvm.iphone.UIPrintInteractionController
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIPrintInteractionController, 7, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_UIPrintInteractionController)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIPrintInteractionController
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_UIPrintInteractionController \
    __INSTANCE_FIELDS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIPrintInteractionController \
    } org_xmlvm_iphone_UIPrintInteractionController

struct org_xmlvm_iphone_UIPrintInteractionController {
    __TIB_DEFINITION_org_xmlvm_iphone_UIPrintInteractionController* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_UIPrintInteractionController;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController
typedef struct org_xmlvm_iphone_UIPrintInteractionController org_xmlvm_iphone_UIPrintInteractionController;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIPrintInteractionController 7

void __INIT_org_xmlvm_iphone_UIPrintInteractionController();
void __INIT_IMPL_org_xmlvm_iphone_UIPrintInteractionController();
void __DELETE_org_xmlvm_iphone_UIPrintInteractionController(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_UIPrintInteractionController(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_UIPrintInteractionController();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UIPrintInteractionController();
JAVA_OBJECT org_xmlvm_iphone_UIPrintInteractionController_sharedPrintController__();
JAVA_BOOLEAN org_xmlvm_iphone_UIPrintInteractionController_isPrintingAvailable__();
JAVA_BOOLEAN org_xmlvm_iphone_UIPrintInteractionController_canPrintData___org_xmlvm_iphone_NSData(JAVA_OBJECT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UIPrintInteractionController_canPrintURL___org_xmlvm_iphone_NSURL(JAVA_OBJECT n1);
JAVA_OBJECT org_xmlvm_iphone_UIPrintInteractionController_printableUTIs__();
void org_xmlvm_iphone_UIPrintInteractionController_presentAnimated___boolean_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler(JAVA_OBJECT me, JAVA_BOOLEAN n1, JAVA_OBJECT n2);
void org_xmlvm_iphone_UIPrintInteractionController_presentFromBarButtonItem___org_xmlvm_iphone_UIBarButtonItem_boolean_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_BOOLEAN n2, JAVA_OBJECT n3);
void org_xmlvm_iphone_UIPrintInteractionController_presentFromRect___org_xmlvm_iphone_CGRect_org_xmlvm_iphone_UIView_boolean_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_BOOLEAN n3, JAVA_OBJECT n4);
void org_xmlvm_iphone_UIPrintInteractionController_dismissAnimated___boolean(JAVA_OBJECT me, JAVA_BOOLEAN n1);
JAVA_OBJECT org_xmlvm_iphone_UIPrintInteractionController_getPrintingItem__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIPrintInteractionController_setPrintingItem___org_xmlvm_iphone_NSObject(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_OBJECT org_xmlvm_iphone_UIPrintInteractionController_getPrintingItems__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIPrintInteractionController_setPrintingItems___java_util_ArrayList(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_UIPrintInteractionController___CLINIT_();

#endif
