#ifndef __ORG_XMLVM_IPHONE_UINAVIGATIONCONTROLLERDELEGATE__
#define __ORG_XMLVM_IPHONE_UINAVIGATIONCONTROLLERDELEGATE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationController
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UINavigationController)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewController
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIViewController)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UINavigationControllerDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UINavigationControllerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UINavigationControllerDelegate_3ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UINavigationControllerDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UINavigationControllerDelegate_1ARRAY;

#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationControllerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationControllerDelegate
typedef struct org_xmlvm_iphone_UINavigationControllerDelegate org_xmlvm_iphone_UINavigationControllerDelegate;
#endif

void __INIT_org_xmlvm_iphone_UINavigationControllerDelegate();

#endif
