#ifndef __ORG_XMLVM_IPHONE_UITEXTVIEWDELEGATE__
#define __ORG_XMLVM_IPHONE_UITEXTVIEWDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "org_xmlvm_iphone_NSObject.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSRange
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSRange
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSRange)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITextView
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITextView
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UITextView)
#endif
// Class declarations for org.xmlvm.iphone.UITextViewDelegate
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UITextViewDelegate, 7, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_UITextViewDelegate)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UITextViewDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UITextViewDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UITextViewDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UITextViewDelegate_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UITextViewDelegate
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_UITextViewDelegate \
    __INSTANCE_FIELDS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UITextViewDelegate \
    } org_xmlvm_iphone_UITextViewDelegate

struct org_xmlvm_iphone_UITextViewDelegate {
    __TIB_DEFINITION_org_xmlvm_iphone_UITextViewDelegate* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_UITextViewDelegate;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITextViewDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITextViewDelegate
typedef struct org_xmlvm_iphone_UITextViewDelegate org_xmlvm_iphone_UITextViewDelegate;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UITextViewDelegate 7

void __INIT_org_xmlvm_iphone_UITextViewDelegate();
void __INIT_IMPL_org_xmlvm_iphone_UITextViewDelegate();
void __DELETE_org_xmlvm_iphone_UITextViewDelegate(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_UITextViewDelegate(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_UITextViewDelegate();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UITextViewDelegate();
void org_xmlvm_iphone_UITextViewDelegate___INIT___(JAVA_OBJECT me);
JAVA_BOOLEAN org_xmlvm_iphone_UITextViewDelegate_textViewShouldBeginEditing___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UITextViewDelegate_textViewShouldEndEditing___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_UITextViewDelegate_textViewDidBeginEditing___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_UITextViewDelegate_textViewDidEndEditing___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UITextViewDelegate_textViewShouldChangeTextInRange___org_xmlvm_iphone_UITextView_org_xmlvm_iphone_NSRange_java_lang_String(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_OBJECT n3);
void org_xmlvm_iphone_UITextViewDelegate_textViewDidChange___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_UITextViewDelegate_textViewDidChangeSelection___org_xmlvm_iphone_UITextView(JAVA_OBJECT me, JAVA_OBJECT n1);

// Define a Macro for the method declarations of the Obj-C wrapper class so that subclass wrappers may easily include these too
#define XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_UITextViewDelegate \
XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_NSObject \

// Define a Macro for the entire contents of the Obj-C wrapper class
#define XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_UITextViewDelegate \
XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_NSObject \


#endif
