#ifndef __ORG_XMLVM_IPHONE_UIIMAGEPICKERCONTROLLER__
#define __ORG_XMLVM_IPHONE_UIIMAGEPICKERCONTROLLER__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "org_xmlvm_iphone_UINavigationController.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
#ifndef XMLVM_FORWARD_DECL_java_util_ArrayList
#define XMLVM_FORWARD_DECL_java_util_ArrayList
XMLVM_FORWARD_DECL(java_util_ArrayList)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGAffineTransform
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGAffineTransform
XMLVM_FORWARD_DECL(org_xmlvm_iphone_CGAffineTransform)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImage
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImage
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIImage)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImagePickerControllerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImagePickerControllerDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIImagePickerControllerDelegate)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImageWriteToPhotoAlbumHandler
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImageWriteToPhotoAlbumHandler
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIImageWriteToPhotoAlbumHandler)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationControllerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationControllerDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UINavigationControllerDelegate)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIView
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIView
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIView)
#endif
// Class declarations for org.xmlvm.iphone.UIImagePickerController
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIImagePickerController, 14, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_UIImagePickerController)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIImagePickerController;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIImagePickerController_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIImagePickerController_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIImagePickerController_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIImagePickerController
#import <UIKit/UIImagePickerController.h>

#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIImagePickerController \
JAVA_OBJECT delegateC; \
id<UIImagePickerControllerDelegate> delegateObjC;
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_UIImagePickerController \
    __INSTANCE_FIELDS_org_xmlvm_iphone_UINavigationController; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIImagePickerController \
    } org_xmlvm_iphone_UIImagePickerController

struct org_xmlvm_iphone_UIImagePickerController {
    __TIB_DEFINITION_org_xmlvm_iphone_UIImagePickerController* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_UIImagePickerController;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImagePickerController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIImagePickerController
typedef struct org_xmlvm_iphone_UIImagePickerController org_xmlvm_iphone_UIImagePickerController;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIImagePickerController 14
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIImagePickerController_getDelegate__ 12
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIImagePickerController_setDelegate___org_xmlvm_iphone_UINavigationControllerDelegate 13

void __INIT_org_xmlvm_iphone_UIImagePickerController();
void __INIT_IMPL_org_xmlvm_iphone_UIImagePickerController();
void __DELETE_org_xmlvm_iphone_UIImagePickerController(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_UIImagePickerController(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_UIImagePickerController();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UIImagePickerController();
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_MediaType();
void org_xmlvm_iphone_UIImagePickerController_PUT_MediaType(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_OriginalImage();
void org_xmlvm_iphone_UIImagePickerController_PUT_OriginalImage(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_EditedImage();
void org_xmlvm_iphone_UIImagePickerController_PUT_EditedImage(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_CropRect();
void org_xmlvm_iphone_UIImagePickerController_PUT_CropRect(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_MediaURL();
void org_xmlvm_iphone_UIImagePickerController_PUT_MediaURL(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_ReferenceURL();
void org_xmlvm_iphone_UIImagePickerController_PUT_ReferenceURL(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_GET_MediaMetadata();
void org_xmlvm_iphone_UIImagePickerController_PUT_MediaMetadata(JAVA_OBJECT v);
void org_xmlvm_iphone_UIImagePickerController___INIT___(JAVA_OBJECT me);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_isSourceTypeAvailable___int(JAVA_INT n1);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_availableMediaTypesForSourceType___int(JAVA_INT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_isCameraDeviceAvailable___int(JAVA_INT n1);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_availableCaptureModesForCameraDevice___int(JAVA_INT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_isFlashAvailableForCameraDevice___int(JAVA_INT n1);
JAVA_INT org_xmlvm_iphone_UIImagePickerController_getSourceType__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setSourceType___int(JAVA_OBJECT me, JAVA_INT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_isAllowsEditing__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setAllowsEditing___boolean(JAVA_OBJECT me, JAVA_BOOLEAN n1);
// Vtable index: 12
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_getDelegate__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setDelegate___org_xmlvm_iphone_UIImagePickerControllerDelegate(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 13
void org_xmlvm_iphone_UIImagePickerController_setDelegate___org_xmlvm_iphone_UINavigationControllerDelegate(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_getMediaTypes__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setMediaTypes___java_util_ArrayList(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_DOUBLE org_xmlvm_iphone_UIImagePickerController_getVideoMaximumDuration__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setVideoMaximumDuration___double(JAVA_OBJECT me, JAVA_DOUBLE n1);
JAVA_INT org_xmlvm_iphone_UIImagePickerController_getVideoQuality__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setVideoQuality___int(JAVA_OBJECT me, JAVA_INT n1);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_getCameraOverlayView__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setCameraOverlayView___org_xmlvm_iphone_UIView(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_OBJECT org_xmlvm_iphone_UIImagePickerController_getCameraViewTransform__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setCameraViewTransform___org_xmlvm_iphone_CGAffineTransform(JAVA_OBJECT me, JAVA_OBJECT n1);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_isShowsCameraControls__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setShowsCameraControls___boolean(JAVA_OBJECT me, JAVA_BOOLEAN n1);
JAVA_INT org_xmlvm_iphone_UIImagePickerController_getCameraCaptureMode__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setCameraCaptureMode___int(JAVA_OBJECT me, JAVA_INT n1);
JAVA_INT org_xmlvm_iphone_UIImagePickerController_getCameraDevice__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setCameraDevice___int(JAVA_OBJECT me, JAVA_INT n1);
JAVA_INT org_xmlvm_iphone_UIImagePickerController_getCameraFlashMode__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_setCameraFlashMode___int(JAVA_OBJECT me, JAVA_INT n1);
void org_xmlvm_iphone_UIImagePickerController_takePicture__(JAVA_OBJECT me);
JAVA_BOOLEAN org_xmlvm_iphone_UIImagePickerController_startVideoCapture__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_stopVideoCapture__(JAVA_OBJECT me);
void org_xmlvm_iphone_UIImagePickerController_UIImageWriteToSavedPhotosAlbum___org_xmlvm_iphone_UIImage_org_xmlvm_iphone_UIImageWriteToPhotoAlbumHandler_java_lang_Object(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_OBJECT n3);

#endif
