#ifndef __ORG_XMLVM_IPHONE_UIGESTURERECOGNIZERDELEGATE__
#define __ORG_XMLVM_IPHONE_UIGESTURERECOGNIZERDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGestureRecognizer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGestureRecognizer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIGestureRecognizer)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITouch
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UITouch
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UITouch)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIGestureRecognizerDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIGestureRecognizerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIGestureRecognizerDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIGestureRecognizerDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIGestureRecognizerDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGestureRecognizerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGestureRecognizerDelegate
typedef struct org_xmlvm_iphone_UIGestureRecognizerDelegate org_xmlvm_iphone_UIGestureRecognizerDelegate;
#endif

void __INIT_org_xmlvm_iphone_UIGestureRecognizerDelegate();
void __INIT_IMPL_org_xmlvm_iphone_UIGestureRecognizerDelegate();

#endif
