#ifndef __ORG_XMLVM_IPHONE_NSERROR_ERRORCODE_NSURL__
#define __ORG_XMLVM_IPHONE_NSERROR_ERRORCODE_NSURL__

#include "xmlvm.h"
#include "java_lang_Object.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
// Class declarations for org.xmlvm.iphone.NSError$ErrorCode$NSURL
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSError_ErrorCode_NSURL, 6, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_NSError_ErrorCode_NSURL)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSError_ErrorCode_NSURL;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSError_ErrorCode_NSURL_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSError_ErrorCode_NSURL_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSError_ErrorCode_NSURL_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSError_ErrorCode_NSURL
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_NSError_ErrorCode_NSURL \
    __INSTANCE_FIELDS_java_lang_Object; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSError_ErrorCode_NSURL \
    } org_xmlvm_iphone_NSError_ErrorCode_NSURL

struct org_xmlvm_iphone_NSError_ErrorCode_NSURL {
    __TIB_DEFINITION_org_xmlvm_iphone_NSError_ErrorCode_NSURL* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_NSError_ErrorCode_NSURL;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError_ErrorCode_NSURL
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError_ErrorCode_NSURL
typedef struct org_xmlvm_iphone_NSError_ErrorCode_NSURL org_xmlvm_iphone_NSError_ErrorCode_NSURL;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_NSError_ErrorCode_NSURL 6

void __INIT_org_xmlvm_iphone_NSError_ErrorCode_NSURL();
void __INIT_IMPL_org_xmlvm_iphone_NSError_ErrorCode_NSURL();
void __DELETE_org_xmlvm_iphone_NSError_ErrorCode_NSURL(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_NSError_ErrorCode_NSURL(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_NSError_ErrorCode_NSURL();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_NSError_ErrorCode_NSURL();
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_Unknown();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_Unknown(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_Cancelled();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_Cancelled(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_BadURL();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_BadURL(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_TimedOut();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_TimedOut(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_UnsupportedURL();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_UnsupportedURL(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotFindHost();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotFindHost(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotConnectToHost();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotConnectToHost(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_DataLengthExceedsMaximum();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_DataLengthExceedsMaximum(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_NetworkConnectionLost();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_NetworkConnectionLost(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_DNSLookupFailed();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_DNSLookupFailed(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_HTTPTooManyRedirects();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_HTTPTooManyRedirects(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ResourceUnavailable();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ResourceUnavailable(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_NotConnectedToInternet();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_NotConnectedToInternet(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_RedirectToNonExistentLocation();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_RedirectToNonExistentLocation(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_BadServerResponse();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_BadServerResponse(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_UserCancelledAuthentication();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_UserCancelledAuthentication(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_UserAuthenticationRequired();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_UserAuthenticationRequired(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ZeroByteResource();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ZeroByteResource(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotDecodeRawData();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotDecodeRawData(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotDecodeContentData();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotDecodeContentData(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotParseResponse();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotParseResponse(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_InternationalRoamingOff();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_InternationalRoamingOff(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CallIsActive();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CallIsActive(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_DataNotAllowed();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_DataNotAllowed(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_RequestBodyStreamExhausted();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_RequestBodyStreamExhausted(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_FileDoesNotExist();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_FileDoesNotExist(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_FileIsDirectory();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_FileIsDirectory(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_NoPermissionsToReadFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_NoPermissionsToReadFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_SecureConnectionFailed();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_SecureConnectionFailed(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ServerCertificateHasBadDate();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ServerCertificateHasBadDate(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ServerCertificateUntrusted();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ServerCertificateUntrusted(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ServerCertificateHasUnknownRoot();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ServerCertificateHasUnknownRoot(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ServerCertificateNotYetValid();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ServerCertificateNotYetValid(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ClientCertificateRejected();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ClientCertificateRejected(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_ClientCertificateRequired();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_ClientCertificateRequired(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotLoadFromNetwork();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotLoadFromNetwork(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotCreateFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotCreateFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotOpenFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotOpenFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotCloseFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotCloseFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotWriteToFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotWriteToFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotRemoveFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotRemoveFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_CannotMoveFile();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_CannotMoveFile(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_DownloadDecodingFailedMidStream();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_DownloadDecodingFailedMidStream(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSError_ErrorCode_NSURL_GET_DownloadDecodingFailedToComplete();
void org_xmlvm_iphone_NSError_ErrorCode_NSURL_PUT_DownloadDecodingFailedToComplete(JAVA_INT v);
void org_xmlvm_iphone_NSError_ErrorCode_NSURL___INIT___(JAVA_OBJECT me);

#endif
