#ifndef __ORG_XMLVM_IPHONE_UIPRINTINTERACTIONCONTROLLER_UIPRINTINTERACTIONCOMPLETIONHANDLER__
#define __ORG_XMLVM_IPHONE_UIPRINTINTERACTIONCONTROLLER_UIPRINTINTERACTIONCOMPLETIONHANDLER__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Preprocessor constants for interfaces:

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSError)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIPrintInteractionController)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler
typedef struct org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler;
#endif

void __INIT_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler();
void __INIT_IMPL_org_xmlvm_iphone_UIPrintInteractionController_UIPrintInteractionCompletionHandler();

#endif
