#ifndef __ORG_XMLVM_IPHONE_UINAVIGATIONBAR__
#define __ORG_XMLVM_IPHONE_UINAVIGATIONBAR__

#include "xmlvm.h"
#include "org_xmlvm_iphone_UIGenericToolbar.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGenericToolbar
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIGenericToolbar
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIGenericToolbar)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationItem
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationItem
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UINavigationItem)
#endif
#ifndef XMLVM_FORWARD_DECL_java_util_ArrayList
#define XMLVM_FORWARD_DECL_java_util_ArrayList
XMLVM_FORWARD_DECL(java_util_ArrayList)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationController
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationController
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UINavigationController)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGRect
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CGRect
XMLVM_FORWARD_DECL(org_xmlvm_iphone_CGRect)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationBarDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationBarDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UINavigationBarDelegate)
#endif
// Class declarations for org.xmlvm.iphone.UINavigationBar
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UINavigationBar, 85)

//XMLVM_BEGIN_MEMBERS
#define __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UINavigationBar
//XMLVM_END_MEMBERS

#define __INSTANCE_MEMBERS_org_xmlvm_iphone_UINavigationBar \
    __INSTANCE_MEMBERS_org_xmlvm_iphone_UIGenericToolbar; \
    struct { \
        JAVA_OBJECT controller_; \
        __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UINavigationBar \
    } org_xmlvm_iphone_UINavigationBar

struct org_xmlvm_iphone_UINavigationBar {
    __CLASS_DEFINITION_org_xmlvm_iphone_UINavigationBar* __class;
    __INSTANCE_MEMBERS_org_xmlvm_iphone_UINavigationBar;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationBar
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UINavigationBar
typedef struct org_xmlvm_iphone_UINavigationBar org_xmlvm_iphone_UINavigationBar;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UINavigationBar 85
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_pushNavigationItem___org_xmlvm_iphone_UINavigationItem_boolean 76
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_popNavigationItemAnimated___boolean 77
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_setItems___java_util_ArrayList 78
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_setItems___java_util_ArrayList_boolean 79
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_getDelegate__ 80
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_setDelegate___org_xmlvm_iphone_UINavigationBarDelegate 81
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_getTopItem__ 82
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_getBackitem__ 83
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_getItems__ 84
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UINavigationBar_updateViews__ 69

void __INIT_org_xmlvm_iphone_UINavigationBar();
JAVA_OBJECT __NEW_org_xmlvm_iphone_UINavigationBar();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UINavigationBar();
void org_xmlvm_iphone_UINavigationBar___INIT___(JAVA_OBJECT me);
void org_xmlvm_iphone_UINavigationBar___INIT____org_xmlvm_iphone_CGRect(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 76
void org_xmlvm_iphone_UINavigationBar_pushNavigationItem___org_xmlvm_iphone_UINavigationItem_boolean(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_BOOLEAN n2);
// Vtable index: 77
JAVA_OBJECT org_xmlvm_iphone_UINavigationBar_popNavigationItemAnimated___boolean(JAVA_OBJECT me, JAVA_BOOLEAN n1);
// Vtable index: 78
void org_xmlvm_iphone_UINavigationBar_setItems___java_util_ArrayList(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 79
void org_xmlvm_iphone_UINavigationBar_setItems___java_util_ArrayList_boolean(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_BOOLEAN n2);
// Vtable index: 80
JAVA_OBJECT org_xmlvm_iphone_UINavigationBar_getDelegate__(JAVA_OBJECT me);
// Vtable index: 81
void org_xmlvm_iphone_UINavigationBar_setDelegate___org_xmlvm_iphone_UINavigationBarDelegate(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 82
JAVA_OBJECT org_xmlvm_iphone_UINavigationBar_getTopItem__(JAVA_OBJECT me);
// Vtable index: 83
JAVA_OBJECT org_xmlvm_iphone_UINavigationBar_getBackitem__(JAVA_OBJECT me);
// Vtable index: 84
JAVA_OBJECT org_xmlvm_iphone_UINavigationBar_getItems__(JAVA_OBJECT me);
// Vtable index: 69
void org_xmlvm_iphone_UINavigationBar_updateViews__(JAVA_OBJECT me);

#endif
