#ifndef __ORG_XMLVM_IPHONE_AVAUDIOPLAYERDELEGATE__
#define __ORG_XMLVM_IPHONE_AVAUDIOPLAYERDELEGATE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Preprocessor constants for interfaces:

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_AVAudioPlayer)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSError)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_AVAudioPlayerDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_AVAudioPlayerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_AVAudioPlayerDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_AVAudioPlayerDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_AVAudioPlayerDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayerDelegate
typedef struct org_xmlvm_iphone_AVAudioPlayerDelegate org_xmlvm_iphone_AVAudioPlayerDelegate;
#endif

void __INIT_org_xmlvm_iphone_AVAudioPlayerDelegate();
void __INIT_IMPL_org_xmlvm_iphone_AVAudioPlayerDelegate();

#endif
