#ifndef __ORG_XMLVM_IPHONE_CAANIMATIONDELEGATE__
#define __ORG_XMLVM_IPHONE_CAANIMATIONDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimation
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimation
XMLVM_FORWARD_DECL(org_xmlvm_iphone_CAAnimation)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimationDelegate_Wrapper
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimationDelegate_Wrapper
XMLVM_FORWARD_DECL(org_xmlvm_iphone_CAAnimationDelegate_Wrapper)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_CAAnimationDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAAnimationDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAAnimationDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAAnimationDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAAnimationDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimationDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAAnimationDelegate
typedef struct org_xmlvm_iphone_CAAnimationDelegate org_xmlvm_iphone_CAAnimationDelegate;
#endif

void __INIT_org_xmlvm_iphone_CAAnimationDelegate();
void __INIT_IMPL_org_xmlvm_iphone_CAAnimationDelegate();

#endif
