#ifndef __ORG_XMLVM_IPHONE_UIACCELEROMETER__
#define __ORG_XMLVM_IPHONE_UIACCELEROMETER__

#include "xmlvm.h"
#include "org_xmlvm_iphone_NSObject.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSObject)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAccelerometerDelegate)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAccelerometer)
#endif
// Class declarations for org.xmlvm.iphone.UIAccelerometer
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIAccelerometer, 16)

//XMLVM_BEGIN_MEMBERS
#define __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UIAccelerometer
//XMLVM_END_MEMBERS

#define __INSTANCE_MEMBERS_org_xmlvm_iphone_UIAccelerometer \
    __INSTANCE_MEMBERS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UIAccelerometer \
    } org_xmlvm_iphone_UIAccelerometer

struct org_xmlvm_iphone_UIAccelerometer {
    __CLASS_DEFINITION_org_xmlvm_iphone_UIAccelerometer* __class;
    __INSTANCE_MEMBERS_org_xmlvm_iphone_UIAccelerometer;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
typedef struct org_xmlvm_iphone_UIAccelerometer org_xmlvm_iphone_UIAccelerometer;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIAccelerometer 16
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIAccelerometer_setUpdateInterval___double 14
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIAccelerometer_setDelegate___org_xmlvm_iphone_UIAccelerometerDelegate 15

void __INIT_org_xmlvm_iphone_UIAccelerometer();
JAVA_OBJECT __NEW_org_xmlvm_iphone_UIAccelerometer();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UIAccelerometer();
void org_xmlvm_iphone_UIAccelerometer___CLINIT_();
JAVA_OBJECT org_xmlvm_iphone_UIAccelerometer_sharedAccelerometer__();
// Vtable index: 14
void org_xmlvm_iphone_UIAccelerometer_setUpdateInterval___double(JAVA_OBJECT me, JAVA_DOUBLE n1);
// Vtable index: 15
void org_xmlvm_iphone_UIAccelerometer_setDelegate___org_xmlvm_iphone_UIAccelerometerDelegate(JAVA_OBJECT me, JAVA_OBJECT n1);

#endif
