#ifndef __ORG_XMLVM_IPHONE_NSNOTIFICATIONCENTER__
#define __ORG_XMLVM_IPHONE_NSNOTIFICATIONCENTER__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "org_xmlvm_iphone_NSObject.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
#ifndef XMLVM_FORWARD_DECL_java_util_Map
#define XMLVM_FORWARD_DECL_java_util_Map
XMLVM_FORWARD_DECL(java_util_Map)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotification
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotification
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNotification)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSNotificationDelegate)
#endif
// Class declarations for org.xmlvm.iphone.NSNotificationCenter
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSNotificationCenter, 7, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_NSNotificationCenter)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationCenter;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationCenter_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationCenter_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSNotificationCenter_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSNotificationCenter
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_NSNotificationCenter \
    __INSTANCE_FIELDS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSNotificationCenter \
    } org_xmlvm_iphone_NSNotificationCenter

struct org_xmlvm_iphone_NSNotificationCenter {
    __TIB_DEFINITION_org_xmlvm_iphone_NSNotificationCenter* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_NSNotificationCenter;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationCenter
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSNotificationCenter
typedef struct org_xmlvm_iphone_NSNotificationCenter org_xmlvm_iphone_NSNotificationCenter;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_NSNotificationCenter 7

void __INIT_org_xmlvm_iphone_NSNotificationCenter();
void __INIT_IMPL_org_xmlvm_iphone_NSNotificationCenter();
void __DELETE_org_xmlvm_iphone_NSNotificationCenter(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_NSNotificationCenter(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_NSNotificationCenter();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_NSNotificationCenter();
JAVA_OBJECT org_xmlvm_iphone_NSNotificationCenter_defaultCenter__();
void org_xmlvm_iphone_NSNotificationCenter___INIT___(JAVA_OBJECT me);
void org_xmlvm_iphone_NSNotificationCenter_addObserver___org_xmlvm_iphone_NSNotificationDelegate_java_lang_String_java_lang_Object(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_OBJECT n3);
void org_xmlvm_iphone_NSNotificationCenter_postNotification___org_xmlvm_iphone_NSNotification(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_NSNotificationCenter_postNotificationName___java_lang_String_java_lang_Object(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
void org_xmlvm_iphone_NSNotificationCenter_postNotificationName___java_lang_String_java_lang_Object_java_util_Map(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_OBJECT n3);
void org_xmlvm_iphone_NSNotificationCenter_removeObserver___java_lang_Object(JAVA_OBJECT me, JAVA_OBJECT n1);
void org_xmlvm_iphone_NSNotificationCenter_removeObserver___java_lang_Object_java_lang_String_java_lang_Object(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2, JAVA_OBJECT n3);

#endif
