#ifndef __ORG_XMLVM_IPHONE_CAMEDIATIMING__
#define __ORG_XMLVM_IPHONE_CAMEDIATIMING__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_CAMediaTiming, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAMediaTiming;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAMediaTiming_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAMediaTiming_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_CAMediaTiming_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAMediaTiming
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_CAMediaTiming
typedef struct org_xmlvm_iphone_CAMediaTiming org_xmlvm_iphone_CAMediaTiming;
#endif

void __INIT_org_xmlvm_iphone_CAMediaTiming();
void __INIT_IMPL_org_xmlvm_iphone_CAMediaTiming();

#endif
