#ifndef __ORG_XMLVM_IPHONE_NSURLCONNECTIONDELEGATE__
#define __ORG_XMLVM_IPHONE_NSURLCONNECTIONDELEGATE__

#include "xmlvm.h"
#include "org_xmlvm_iphone_NSObject.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSObject
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSObject)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSData
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSData
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSData)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLConnection
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLConnection
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSURLConnection)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSError)
#endif
// Class declarations for org.xmlvm.iphone.NSURLConnectionDelegate
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSURLConnectionDelegate, 17)

//XMLVM_BEGIN_MEMBERS
#define __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_NSURLConnectionDelegate
//XMLVM_END_MEMBERS

#define __INSTANCE_MEMBERS_org_xmlvm_iphone_NSURLConnectionDelegate \
    __INSTANCE_MEMBERS_org_xmlvm_iphone_NSObject; \
    struct { \
        __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_NSURLConnectionDelegate \
    } org_xmlvm_iphone_NSURLConnectionDelegate

struct org_xmlvm_iphone_NSURLConnectionDelegate {
    __CLASS_DEFINITION_org_xmlvm_iphone_NSURLConnectionDelegate* __class;
    __INSTANCE_MEMBERS_org_xmlvm_iphone_NSURLConnectionDelegate;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLConnectionDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLConnectionDelegate
typedef struct org_xmlvm_iphone_NSURLConnectionDelegate org_xmlvm_iphone_NSURLConnectionDelegate;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_NSURLConnectionDelegate 17
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidFinishLoading___org_xmlvm_iphone_NSURLConnection 14
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidFailWithError___org_xmlvm_iphone_NSURLConnection_org_xmlvm_iphone_NSError 15
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidReceiveData___org_xmlvm_iphone_NSURLConnection_org_xmlvm_iphone_NSData 16

void __INIT_org_xmlvm_iphone_NSURLConnectionDelegate();
JAVA_OBJECT __NEW_org_xmlvm_iphone_NSURLConnectionDelegate();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_NSURLConnectionDelegate();
void org_xmlvm_iphone_NSURLConnectionDelegate___INIT___(JAVA_OBJECT me);
// Vtable index: 14
void org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidFinishLoading___org_xmlvm_iphone_NSURLConnection(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 15
void org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidFailWithError___org_xmlvm_iphone_NSURLConnection_org_xmlvm_iphone_NSError(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
// Vtable index: 16
void org_xmlvm_iphone_NSURLConnectionDelegate_connectionDidReceiveData___org_xmlvm_iphone_NSURLConnection_org_xmlvm_iphone_NSData(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);

#endif
