#ifndef __ORG_XMLVM_IPHONE_UIALERTVIEW_BUTTONCLICKCALLBACK__
#define __ORG_XMLVM_IPHONE_UIALERTVIEW_BUTTONCLICKCALLBACK__

#include "xmlvm.h"
#include "java_lang_Object.h"
#include "org_xmlvm_iphone_UIControlDelegate.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAlertView
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAlertView
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAlertView)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIControl
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIControl
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIControl)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIControlDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIControlDelegate
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIControlDelegate)
#endif
// Class declarations for org.xmlvm.iphone.UIAlertView$ButtonClickCallback
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIAlertView_ButtonClickCallback, 12)

//XMLVM_BEGIN_MEMBERS
#define __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UIAlertView_ButtonClickCallback
//XMLVM_END_MEMBERS

#define __INSTANCE_MEMBERS_org_xmlvm_iphone_UIAlertView_ButtonClickCallback \
    __INSTANCE_MEMBERS_java_lang_Object; \
    struct { \
        JAVA_OBJECT this_0_; \
        __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_UIAlertView_ButtonClickCallback \
    } org_xmlvm_iphone_UIAlertView_ButtonClickCallback

struct org_xmlvm_iphone_UIAlertView_ButtonClickCallback {
    __CLASS_DEFINITION_org_xmlvm_iphone_UIAlertView_ButtonClickCallback* __class;
    __INSTANCE_MEMBERS_org_xmlvm_iphone_UIAlertView_ButtonClickCallback;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAlertView_ButtonClickCallback
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAlertView_ButtonClickCallback
typedef struct org_xmlvm_iphone_UIAlertView_ButtonClickCallback org_xmlvm_iphone_UIAlertView_ButtonClickCallback;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIAlertView_ButtonClickCallback 12
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_UIAlertView_ButtonClickCallback_raiseEvent___org_xmlvm_iphone_UIControl_int 11

void __INIT_org_xmlvm_iphone_UIAlertView_ButtonClickCallback();
JAVA_OBJECT __NEW_org_xmlvm_iphone_UIAlertView_ButtonClickCallback();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UIAlertView_ButtonClickCallback();
void org_xmlvm_iphone_UIAlertView_ButtonClickCallback___INIT____org_xmlvm_iphone_UIAlertView_int(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_INT n2);
// Vtable index: 11
void org_xmlvm_iphone_UIAlertView_ButtonClickCallback_raiseEvent___org_xmlvm_iphone_UIControl_int(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_INT n2);

#endif
