#ifndef __ORG_XMLVM_IPHONE_AVAUDIOPLAYER_LISTENER__
#define __ORG_XMLVM_IPHONE_AVAUDIOPLAYER_LISTENER__

#include "xmlvm.h"
#include "java_lang_Object.h"
#include "java_lang_Object.h"
#include "javazoom_jlgui_basicplayer_BasicPlayerListener.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicPlayerEvent
#define XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicPlayerEvent
XMLVM_FORWARD_DECL(javazoom_jlgui_basicplayer_BasicPlayerEvent)
#endif
#ifndef XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicPlayerListener
#define XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicPlayerListener
XMLVM_FORWARD_DECL(javazoom_jlgui_basicplayer_BasicPlayerListener)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_AVAudioPlayer)
#endif
#ifndef XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicController
#define XMLVM_FORWARD_DECL_javazoom_jlgui_basicplayer_BasicController
XMLVM_FORWARD_DECL(javazoom_jlgui_basicplayer_BasicController)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_java_util_Map
#define XMLVM_FORWARD_DECL_java_util_Map
XMLVM_FORWARD_DECL(java_util_Map)
#endif
// Class declarations for org.xmlvm.iphone.AVAudioPlayer$Listener
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_AVAudioPlayer_Listener, 15)

//XMLVM_BEGIN_MEMBERS
#define __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_AVAudioPlayer_Listener
//XMLVM_END_MEMBERS

#define __INSTANCE_MEMBERS_org_xmlvm_iphone_AVAudioPlayer_Listener \
    __INSTANCE_MEMBERS_java_lang_Object; \
    struct { \
        JAVA_OBJECT this_0_; \
        __ADDITIONAL_INSTANCE_MEMBERS_org_xmlvm_iphone_AVAudioPlayer_Listener \
    } org_xmlvm_iphone_AVAudioPlayer_Listener

struct org_xmlvm_iphone_AVAudioPlayer_Listener {
    __CLASS_DEFINITION_org_xmlvm_iphone_AVAudioPlayer_Listener* __class;
    __INSTANCE_MEMBERS_org_xmlvm_iphone_AVAudioPlayer_Listener;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer_Listener
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_AVAudioPlayer_Listener
typedef struct org_xmlvm_iphone_AVAudioPlayer_Listener org_xmlvm_iphone_AVAudioPlayer_Listener;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_AVAudioPlayer_Listener 15
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_AVAudioPlayer_Listener_opened___java_lang_Object_java_util_Map 11
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_AVAudioPlayer_Listener_progress___int_long_byte_ARRAYTYPE_java_util_Map 12
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_AVAudioPlayer_Listener_setController___javazoom_jlgui_basicplayer_BasicController 13
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_AVAudioPlayer_Listener_stateUpdated___javazoom_jlgui_basicplayer_BasicPlayerEvent 14

void __INIT_org_xmlvm_iphone_AVAudioPlayer_Listener();
JAVA_OBJECT __NEW_org_xmlvm_iphone_AVAudioPlayer_Listener();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_AVAudioPlayer_Listener();
void org_xmlvm_iphone_AVAudioPlayer_Listener___INIT____org_xmlvm_iphone_AVAudioPlayer_org_xmlvm_iphone_AVAudioPlayer(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
// Vtable index: 11
void org_xmlvm_iphone_AVAudioPlayer_Listener_opened___java_lang_Object_java_util_Map(JAVA_OBJECT me, JAVA_OBJECT n1, JAVA_OBJECT n2);
// Vtable index: 12
void org_xmlvm_iphone_AVAudioPlayer_Listener_progress___int_long_byte_ARRAYTYPE_java_util_Map(JAVA_OBJECT me, JAVA_INT n1, JAVA_LONG n2, JAVA_OBJECT n3, JAVA_OBJECT n4);
// Vtable index: 13
void org_xmlvm_iphone_AVAudioPlayer_Listener_setController___javazoom_jlgui_basicplayer_BasicController(JAVA_OBJECT me, JAVA_OBJECT n1);
// Vtable index: 14
void org_xmlvm_iphone_AVAudioPlayer_Listener_stateUpdated___javazoom_jlgui_basicplayer_BasicPlayerEvent(JAVA_OBJECT me, JAVA_OBJECT n1);

#endif
