#ifndef __ORG_XMLVM_IPHONE_UIAPPLICATIONLAUNCHOPTIONS__
#define __ORG_XMLVM_IPHONE_UIAPPLICATIONLAUNCHOPTIONS__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
// Class declarations for org.xmlvm.iphone.UIApplicationLaunchOptions
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIApplicationLaunchOptions, 6, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_UIApplicationLaunchOptions)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIApplicationLaunchOptions;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIApplicationLaunchOptions_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIApplicationLaunchOptions_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIApplicationLaunchOptions_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIApplicationLaunchOptions
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_UIApplicationLaunchOptions \
    __INSTANCE_FIELDS_java_lang_Object; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_UIApplicationLaunchOptions \
    } org_xmlvm_iphone_UIApplicationLaunchOptions

struct org_xmlvm_iphone_UIApplicationLaunchOptions {
    __TIB_DEFINITION_org_xmlvm_iphone_UIApplicationLaunchOptions* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_UIApplicationLaunchOptions;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIApplicationLaunchOptions
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIApplicationLaunchOptions
typedef struct org_xmlvm_iphone_UIApplicationLaunchOptions org_xmlvm_iphone_UIApplicationLaunchOptions;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_UIApplicationLaunchOptions 6

void __INIT_org_xmlvm_iphone_UIApplicationLaunchOptions();
void __INIT_IMPL_org_xmlvm_iphone_UIApplicationLaunchOptions();
void __DELETE_org_xmlvm_iphone_UIApplicationLaunchOptions(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_UIApplicationLaunchOptions(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_UIApplicationLaunchOptions();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_UIApplicationLaunchOptions();
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_URLKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_URLKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_SourceApplicationKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_SourceApplicationKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_RemoteNotificationKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_RemoteNotificationKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_AnnotationKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_AnnotationKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_LocalNotificationKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_LocalNotificationKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_LocationKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_LocationKey(JAVA_OBJECT v);
JAVA_OBJECT org_xmlvm_iphone_UIApplicationLaunchOptions_GET_NewsstandDownloadsKey();
void org_xmlvm_iphone_UIApplicationLaunchOptions_PUT_NewsstandDownloadsKey(JAVA_OBJECT v);

// Define a Macro for the method declarations of the Obj-C wrapper class so that subclass wrappers may easily include these too
#define XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_UIApplicationLaunchOptions \

// Define a Macro for the entire contents of the Obj-C wrapper class
#define XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_UIApplicationLaunchOptions \


#endif
