#ifndef __ORG_XMLVM_IPHONE_NSURLREQUESTCACHEPOLICY__
#define __ORG_XMLVM_IPHONE_NSURLREQUESTCACHEPOLICY__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
// Class declarations for org.xmlvm.iphone.NSURLRequestCachePolicy
XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSURLRequestCachePolicy, 6, XMLVM_ITABLE_SIZE_org_xmlvm_iphone_NSURLRequestCachePolicy)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSURLRequestCachePolicy;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSURLRequestCachePolicy_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSURLRequestCachePolicy_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSURLRequestCachePolicy_3ARRAY;
//XMLVM_BEGIN_DECLARATIONS
#define __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSURLRequestCachePolicy
//XMLVM_END_DECLARATIONS

#define __INSTANCE_FIELDS_org_xmlvm_iphone_NSURLRequestCachePolicy \
    __INSTANCE_FIELDS_java_lang_Object; \
    struct { \
        __ADDITIONAL_INSTANCE_FIELDS_org_xmlvm_iphone_NSURLRequestCachePolicy \
    } org_xmlvm_iphone_NSURLRequestCachePolicy

struct org_xmlvm_iphone_NSURLRequestCachePolicy {
    __TIB_DEFINITION_org_xmlvm_iphone_NSURLRequestCachePolicy* tib;
    struct {
        __INSTANCE_FIELDS_org_xmlvm_iphone_NSURLRequestCachePolicy;
    } fields;
};
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLRequestCachePolicy
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSURLRequestCachePolicy
typedef struct org_xmlvm_iphone_NSURLRequestCachePolicy org_xmlvm_iphone_NSURLRequestCachePolicy;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_NSURLRequestCachePolicy 6

void __INIT_org_xmlvm_iphone_NSURLRequestCachePolicy();
void __INIT_IMPL_org_xmlvm_iphone_NSURLRequestCachePolicy();
void __DELETE_org_xmlvm_iphone_NSURLRequestCachePolicy(void* me, void* client_data);
void __INIT_INSTANCE_MEMBERS_org_xmlvm_iphone_NSURLRequestCachePolicy(JAVA_OBJECT me, int derivedClassWillRegisterFinalizer);
JAVA_OBJECT __NEW_org_xmlvm_iphone_NSURLRequestCachePolicy();
JAVA_OBJECT __NEW_INSTANCE_org_xmlvm_iphone_NSURLRequestCachePolicy();
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_UseProtocolCachePolicy();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_UseProtocolCachePolicy(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReloadIgnoringLocalCacheData();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReloadIgnoringLocalCacheData(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReloadIgnoringLocalAndRemoteCacheData();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReloadIgnoringLocalAndRemoteCacheData(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReloadIgnoringCacheData();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReloadIgnoringCacheData(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReturnCacheDataElseLoad();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReturnCacheDataElseLoad(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReturnCacheDataDontLoad();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReturnCacheDataDontLoad(JAVA_INT v);
JAVA_INT org_xmlvm_iphone_NSURLRequestCachePolicy_GET_ReloadRevalidatingCacheData();
void org_xmlvm_iphone_NSURLRequestCachePolicy_PUT_ReloadRevalidatingCacheData(JAVA_INT v);

// Define a Macro for the method declarations of the Obj-C wrapper class so that subclass wrappers may easily include these too
#define XMLVM_OBJC_OVERRIDE_CLASS_DECLARATIONS_org_xmlvm_iphone_NSURLRequestCachePolicy \

// Define a Macro for the entire contents of the Obj-C wrapper class
#define XMLVM_OBJC_OVERRIDE_CLASS_DEFINITIONS_org_xmlvm_iphone_NSURLRequestCachePolicy \


#endif
