#ifndef __ORG_XMLVM_IPHONE_UIVIEWANIMATIONDELEGATE__
#define __ORG_XMLVM_IPHONE_UIVIEWANIMATIONDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewAnimationDelegate_Wrapper
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewAnimationDelegate_Wrapper
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIViewAnimationDelegate_Wrapper)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIViewAnimationDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIViewAnimationDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIViewAnimationDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIViewAnimationDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIViewAnimationDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewAnimationDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIViewAnimationDelegate
typedef struct org_xmlvm_iphone_UIViewAnimationDelegate org_xmlvm_iphone_UIViewAnimationDelegate;
#endif

void __INIT_org_xmlvm_iphone_UIViewAnimationDelegate();
void __INIT_IMPL_org_xmlvm_iphone_UIViewAnimationDelegate();

#endif
