#ifndef __ORG_XMLVM_IPHONE_GL_EAGLDRAWABLE__
#define __ORG_XMLVM_IPHONE_GL_EAGLDRAWABLE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_gl_EAGLDrawable, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_gl_EAGLDrawable;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_gl_EAGLDrawable_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_gl_EAGLDrawable_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_gl_EAGLDrawable_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_gl_EAGLDrawable
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_gl_EAGLDrawable
typedef struct org_xmlvm_iphone_gl_EAGLDrawable org_xmlvm_iphone_gl_EAGLDrawable;
#endif

void __INIT_org_xmlvm_iphone_gl_EAGLDrawable();
void __INIT_IMPL_org_xmlvm_iphone_gl_EAGLDrawable();

#endif
