#ifndef __ORG_XMLVM_IPHONE_NSTIMERDELEGATE__
#define __ORG_XMLVM_IPHONE_NSTIMERDELEGATE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Preprocessor constants for interfaces:

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSTimer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSTimer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSTimer)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_NSTimerDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSTimerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSTimerDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSTimerDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_NSTimerDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSTimerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSTimerDelegate
typedef struct org_xmlvm_iphone_NSTimerDelegate org_xmlvm_iphone_NSTimerDelegate;
#endif

void __INIT_org_xmlvm_iphone_NSTimerDelegate();
void __INIT_IMPL_org_xmlvm_iphone_NSTimerDelegate();

#endif
