#ifndef __ORG_XMLVM_IPHONE_UIACCELEROMETERDELEGATE__
#define __ORG_XMLVM_IPHONE_UIACCELEROMETERDELEGATE__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAcceleration
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAcceleration
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAcceleration)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometer
XMLVM_FORWARD_DECL(org_xmlvm_iphone_UIAccelerometer)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_UIAccelerometerDelegate, 0, 0)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate_1ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_UIAccelerometerDelegate_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_UIAccelerometerDelegate
typedef struct org_xmlvm_iphone_UIAccelerometerDelegate org_xmlvm_iphone_UIAccelerometerDelegate;
#endif

void __INIT_org_xmlvm_iphone_UIAccelerometerDelegate();
void __INIT_IMPL_org_xmlvm_iphone_UIAccelerometerDelegate();

#endif
