#ifndef __ORG_XMLVM_IPHONE_GKSESSIONDELEGATE__
#define __ORG_XMLVM_IPHONE_GKSESSIONDELEGATE__

#include "xmlvm.h"
#include "java_lang_Object.h"

// Circular references:
#ifndef XMLVM_FORWARD_DECL_java_lang_Object
#define XMLVM_FORWARD_DECL_java_lang_Object
XMLVM_FORWARD_DECL(java_lang_Object)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_GKSession
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_GKSession
XMLVM_FORWARD_DECL(org_xmlvm_iphone_GKSession)
#endif
#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_NSError
XMLVM_FORWARD_DECL(org_xmlvm_iphone_NSError)
#endif
#ifndef XMLVM_FORWARD_DECL_java_lang_String
#define XMLVM_FORWARD_DECL_java_lang_String
XMLVM_FORWARD_DECL(java_lang_String)
#endif

XMLVM_DEFINE_CLASS(org_xmlvm_iphone_GKSessionDelegate, 15)

extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_GKSessionDelegate;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_GKSessionDelegate_3ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_GKSessionDelegate_2ARRAY;
extern JAVA_OBJECT __CLASS_org_xmlvm_iphone_GKSessionDelegate_1ARRAY;

#ifndef XMLVM_FORWARD_DECL_org_xmlvm_iphone_GKSessionDelegate
#define XMLVM_FORWARD_DECL_org_xmlvm_iphone_GKSessionDelegate
typedef struct org_xmlvm_iphone_GKSessionDelegate org_xmlvm_iphone_GKSessionDelegate;
#endif

#define XMLVM_VTABLE_SIZE_org_xmlvm_iphone_GKSessionDelegate 15
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_GKSessionDelegate_didChangeState___org_xmlvm_iphone_GKSession_java_lang_String_int 11
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_GKSessionDelegate_didReceiveConnectionRequestFromPeer___org_xmlvm_iphone_GKSession_java_lang_String 12
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_GKSessionDelegate_connectionWithPeerFailed___org_xmlvm_iphone_GKSession_java_lang_String_org_xmlvm_iphone_NSError 13
#define XMLVM_VTABLE_IDX_org_xmlvm_iphone_GKSessionDelegate_didFailWithError___org_xmlvm_iphone_GKSession_org_xmlvm_iphone_NSError 14

void __INIT_FOR_CLASS_org_xmlvm_iphone_GKSessionDelegate(__TIB_DEFINITION_TEMPLATE** interface);
void __INIT_IMPL_FOR_CLASS_org_xmlvm_iphone_GKSessionDelegate(__TIB_DEFINITION_TEMPLATE** interface);
void __INIT_org_xmlvm_iphone_GKSessionDelegate();

#endif
