// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows {
public class HorizontalAlignment: global::Compatlib.System.Object {

static HorizontalAlignment() {
    @static();
}

public static Compatlib.System.Windows.HorizontalAlignment _fStretch;

public static Compatlib.System.Windows.HorizontalAlignment _fLeft;

public static new void @static(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.HorizontalAlignment: void <clinit>()]
    _fStretch = new Compatlib.System.Windows.HorizontalAlignment();
    _fStretch.horizontalAlignment = global::System.Windows.HorizontalAlignment.Stretch;

    _fLeft = new Compatlib.System.Windows.HorizontalAlignment();
    _fLeft.horizontalAlignment = global::System.Windows.HorizontalAlignment.Left;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.HorizontalAlignment: void <clinit>()]
}

public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.HorizontalAlignment: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.HorizontalAlignment: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.HorizontalAlignment]
public global::System.Windows.HorizontalAlignment horizontalAlignment;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.HorizontalAlignment]

} // end of class: HorizontalAlignment

} // end of namespace: Compatlib.System.Windows
