// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows {
public class MessageBoxResult: global::Compatlib.System.Object {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.MessageBoxResult: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.MessageBoxResult: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.MessageBoxResult]
public global::System.Windows.MessageBoxResult messageBoxResult;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.MessageBoxResult]

} // end of class: MessageBoxResult

} // end of namespace: Compatlib.System.Windows
