// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows {
public class RoutedEventArgs: global::Compatlib.System.EventArgs {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: void <init>()]
}

public virtual global::System.Object getOriginalSource(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: Compatlib.System.Object getOriginalSource()]
    return originalSource;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.RoutedEventArgs: Compatlib.System.Object getOriginalSource()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.RoutedEventArgs]
public global::System.Windows.RoutedEventArgs args;
public Compatlib.System.Object originalSource;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.RoutedEventArgs]

} // end of class: RoutedEventArgs

} // end of namespace: Compatlib.System.Windows
