// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows {
public class StartupEventHandler: global::Compatlib.System.EventHandler {
public new void @this(Compatlib.System.Object n1, Compatlib.System.String n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.StartupEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
    base.@this(n1, n2);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.StartupEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.StartupEventHandler]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.StartupEventHandler]

} // end of class: StartupEventHandler

} // end of namespace: Compatlib.System.Windows
