// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows {
public class Thickness: global::java.lang.Object {
public void @this(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Thickness: void <init>(double)]
    thickness = new global::System.Windows.Thickness(n1);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Thickness: void <init>(double)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Thickness]
public global::System.Windows.Thickness thickness;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Thickness]

} // end of class: Thickness

} // end of namespace: Compatlib.System.Windows
