// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace org.apache.harmony.niochar.charset.additional {
public class windows_11255_2Encoder: global::java.nio.charset.CharsetEncoder {
private void nEncode(long n1, int n2, global::org.xmlvm._nArrayAdapter<char> n3, int n4, global::org.xmlvm._nArrayAdapter<int> n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.windows_1255$Encoder: void nEncode(long, int, char[], int, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.windows_1255$Encoder: void nEncode(long, int, char[], int, int[])]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.windows_1255$Encoder]
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.windows_1255$Encoder]

} // end of class: windows_11255_2Encoder

} // end of namespace: org.apache.harmony.niochar.charset.additional
