// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace org.apache.harmony.niochar.charset.additional {
public class x_1MS950_1HKSCS_2Encoder: global::java.nio.charset.CharsetEncoder {
private void nEncode(long n1, int n2, int n3, global::org.xmlvm._nArrayAdapter<char> n4, int n5, global::org.xmlvm._nArrayAdapter<int> n6){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.x_MS950_HKSCS$Encoder: void nEncode(long, int, int, char[], int, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.x_MS950_HKSCS$Encoder: void nEncode(long, int, int, char[], int, int[])]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.x_MS950_HKSCS$Encoder]
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.x_MS950_HKSCS$Encoder]

} // end of class: x_1MS950_1HKSCS_2Encoder

} // end of namespace: org.apache.harmony.niochar.charset.additional
