// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace org.apache.harmony.niochar.charset.additional {
public class x_1windows_1949_2Decoder: global::java.nio.charset.CharsetDecoder {
public virtual void nDecode(global::org.xmlvm._nArrayAdapter<char> n1, int n2, int n3, long n4, int n5, global::org.xmlvm._nArrayAdapter<int> n6){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.x_windows_949$Decoder: void nDecode(char[], int, int, long, int, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.x_windows_949$Decoder: void nDecode(char[], int, int, long, int, int[])]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.niochar.charset.additional.x_windows_949$Decoder]
//XMLVM_END_WRAPPER[org.apache.harmony.niochar.charset.additional.x_windows_949$Decoder]

} // end of class: x_1windows_1949_2Decoder

} // end of namespace: org.apache.harmony.niochar.charset.additional
