// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.System.Windows.Controls {
public class Button: global::Compatlib.System.Windows.Controls.Primitives.ButtonBase {
public new void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Button: void <init>()]
    base.element = new global::System.Windows.Controls.Button();
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Button: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.Button]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.Button]

} // end of class: Button

} // end of namespace: Compatlib.System.Windows.Controls
