// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Controls {
public class ContentControl: global::Compatlib.System.Windows.Controls.Control {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: void <init>()]
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: void <init>()]
}

public virtual global::System.Object getContent(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: Compatlib.System.Object getContent()]
    return this.content;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: Compatlib.System.Object getContent()]
}

public virtual void setContent(global::Compatlib.System.Object n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: void setContent(Compatlib.System.Object)]
    this.content = n1;
    if (n1 is Compatlib.System.String)
    {
        ((global::System.Windows.Controls.ContentControl)base.element).Content = org.xmlvm._nUtil.toNativeString(((Compatlib.System.String)n1)._fvalue);
    }
    else
    {
        throw new global::System.Exception("Content not implemented");
    }
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.ContentControl: void setContent(Compatlib.System.Object)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.ContentControl]
private Compatlib.System.Object content;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.ContentControl]

} // end of class: ContentControl

} // end of namespace: Compatlib.System.Windows.Controls
