// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Windows.Controls {
public class StackPanel: global::Compatlib.System.Windows.Controls.Panel {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.StackPanel: void <init>()]
    base.element = new global::System.Windows.Controls.StackPanel();
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.StackPanel: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.StackPanel]
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.StackPanel]

} // end of class: StackPanel

} // end of namespace: Compatlib.System.Windows.Controls
