// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace Compatlib.System.Windows.Controls {
public class TextBlock: global::Compatlib.System.Windows.FrameworkElement {
public virtual global::System.Object getForeground(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.Windows.Media.Brush getForeground()]
    return this.foreground;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.Windows.Media.Brush getForeground()]
}

public virtual void setForeground(global::Compatlib.System.Windows.Media.Brush n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setForeground(Compatlib.System.Windows.Media.Brush)]
    this.foreground = n1;
    ((global::System.Windows.Controls.TextBlock)base.element).Foreground = n1.brush;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setForeground(Compatlib.System.Windows.Media.Brush)]
}

public virtual global::System.Object getText(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.String getText()]
    string nativeText = ((global::System.Windows.Controls.TextBlock)base.element).Text;
    java.lang.String temp = org.xmlvm._nUtil.toJavaString(nativeText);
    Compatlib.System.String compatText = new Compatlib.System.String();
    compatText.@this(temp);
    return compatText;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.String getText()]
}

public virtual void setText(global::Compatlib.System.String n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setText(Compatlib.System.String)]
    ((global::System.Windows.Controls.TextBlock)base.element).Text = org.xmlvm._nUtil.toNativeString(n1._fvalue);
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setText(Compatlib.System.String)]
}

public virtual global::System.Object getFontFamily(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.Windows.Media.FontFamily getFontFamily()]
    global::Compatlib.System.Windows.Media.FontFamily f = new global::Compatlib.System.Windows.Media.FontFamily();
    f.@this();
    f.fontFamily = ((global::System.Windows.Controls.TextBlock)base.element).FontFamily;
    return f;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: Compatlib.System.Windows.Media.FontFamily getFontFamily()]
}

public virtual void setFontFamily(global::Compatlib.System.Windows.Media.FontFamily n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setFontFamily(Compatlib.System.Windows.Media.FontFamily)]
    //this.fontFamily = n1;
    ((global::System.Windows.Controls.TextBlock)base.element).FontFamily = n1.fontFamily;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setFontFamily(Compatlib.System.Windows.Media.FontFamily)]
}

public virtual double getFontSize(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: double getFontSize()]
    return ((global::System.Windows.Controls.TextBlock)base.element).FontSize;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: double getFontSize()]
}

public virtual void setFontSize(double n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setFontSize(double)]
    ((global::System.Windows.Controls.TextBlock)base.element).FontSize = n1;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void setFontSize(double)]
}

public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void <init>()]
    base.element = new global::System.Windows.Controls.TextBlock();
    base.@this();
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock: void <init>()]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Windows.Controls.TextBlock]
private Compatlib.System.Windows.Media.Brush foreground;
//private Compatlib.System.Windows.Media.FontFamily fontFamily;
//XMLVM_END_WRAPPER[Compatlib.System.Windows.Controls.TextBlock]

} // end of class: TextBlock

} // end of namespace: Compatlib.System.Windows.Controls
