// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.concurrent.atomic {
public class AtomicLong: global::java.lang.Number,global::java.io.Serializable {
private static bool VMSupportsCS8(){
//XMLVM_BEGIN_WRAPPER[java.util.concurrent.atomic.AtomicLong: boolean VMSupportsCS8()]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.concurrent.atomic.AtomicLong: boolean VMSupportsCS8()]
}

//XMLVM_BEGIN_WRAPPER[java.util.concurrent.atomic.AtomicLong]
//XMLVM_END_WRAPPER[java.util.concurrent.atomic.AtomicLong]

} // end of class: AtomicLong

} // end of namespace: java.util.concurrent.atomic
