// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.Diagnostics {
public class Debug: global::Compatlib.System.Object {
public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Diagnostics.Debug: void <init>()]
//XMLVM_END_WRAPPER[Compatlib.System.Diagnostics.Debug: void <init>()]
}

public static void WriteLine(global::Compatlib.System.Object n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.Diagnostics.Debug: void WriteLine(Compatlib.System.Object)]
//XMLVM_END_WRAPPER[Compatlib.System.Diagnostics.Debug: void WriteLine(Compatlib.System.Object)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.Diagnostics.Debug]
//XMLVM_END_WRAPPER[Compatlib.System.Diagnostics.Debug]

} // end of class: Debug

} // end of namespace: Compatlib.System.Diagnostics
