// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.prefs {
public class RegistryPreferencesImpl: global::java.util.prefs.AbstractPreferences {
private global::System.Object getValue(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, bool n3, global::org.xmlvm._nArrayAdapter<int> n4){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[] getValue(byte[], byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[] getValue(byte[], byte[], boolean, int[])]
}

private void putValue(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, global::org.xmlvm._nArrayAdapter<sbyte> n3, bool n4, global::org.xmlvm._nArrayAdapter<int> n5){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void putValue(byte[], byte[], byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void putValue(byte[], byte[], byte[], boolean, int[])]
}

private void removeKey(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, bool n3, global::org.xmlvm._nArrayAdapter<int> n4){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void removeKey(byte[], byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void removeKey(byte[], byte[], boolean, int[])]
}

private global::System.Object keys(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, global::org.xmlvm._nArrayAdapter<int> n3){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[][] keys(byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[][] keys(byte[], boolean, int[])]
}

private void removeNode(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, bool n3, global::org.xmlvm._nArrayAdapter<int> n4){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void removeNode(byte[], byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void removeNode(byte[], byte[], boolean, int[])]
}

private bool getNode(global::org.xmlvm._nArrayAdapter<sbyte> n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, bool n3, global::org.xmlvm._nArrayAdapter<int> n4){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: boolean getNode(byte[], byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: boolean getNode(byte[], byte[], boolean, int[])]
}

private global::System.Object getChildNames(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, global::org.xmlvm._nArrayAdapter<int> n3){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[][] getChildNames(byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: byte[][] getChildNames(byte[], boolean, int[])]
}

private void flushPrefs(global::org.xmlvm._nArrayAdapter<sbyte> n1, bool n2, global::org.xmlvm._nArrayAdapter<int> n3){
//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void flushPrefs(byte[], boolean, int[])]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl: void flushPrefs(byte[], boolean, int[])]
}

//XMLVM_BEGIN_WRAPPER[java.util.prefs.RegistryPreferencesImpl]
//XMLVM_END_WRAPPER[java.util.prefs.RegistryPreferencesImpl]

} // end of class: RegistryPreferencesImpl

} // end of namespace: java.util.prefs
