/* Copyright (c) 2002-2011 by XMLVM.org
 *
 * Project Info:  http://www.xmlvm.org
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

package org.xmlvm.tutorial.android.helloworld.decl;

import android.app.Activity;
import android.os.Bundle;

/**
 * This version of Hello World uses a declarative layout and is functionally
 * identical to the programmatic version. The layout is described in a layout
 * file using XML syntax. It describes the view hierarchy with all necessary
 * layout parameters. Directory <code>res/layout/</code> contains the file
 * <code>main.xml</code>. The Android SDK will use the basename of the file to
 * generate a Java identifier with a unique ID in the so-called <code>R</code>
 * -class. It can be referenced via <code>R.layout.main</code>.
 */
public class HelloWorldActivity extends Activity {

    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        /*
         * The overloaded version of method setContentView() take an ID as a
         * parameter. The ID is referenced via the R-class generated by the
         * Android SDK. The ID is used to local the matching main.xml file whose
         * content is parsed to build up the view hierarchy.
         */
        setContentView(R.layout.main);
    }
}