// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.ComponentModel {
public class BackgroundWorker: global::Compatlib.System.Object {
public global::Compatlib.System.ComponentModel.DoWorkEvent _fDoWork;

public void @this(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void <init>()]
    _fDoWork = new DoWorkEvent();
    _fDoWork.@this();

    bw.DoWork += DoWorkHandler;
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void <init>()]
}

public virtual void RunWorkerAsync(int n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void RunWorkerAsync(int)]
    bw.RunWorkerAsync(n1);
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void RunWorkerAsync(int)]
}

public virtual void CancelAsync(){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void CancelAsync()]
    bw.CancelAsync();
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void CancelAsync()]
}

public virtual void setWorkerSupportsCancellation(bool n1){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void setWorkerSupportsCancellation(boolean)]
    bw.WorkerSupportsCancellation = n1;
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker: void setWorkerSupportsCancellation(boolean)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker]
private global::System.ComponentModel.BackgroundWorker bw = new global::System.ComponentModel.BackgroundWorker();

public void DoWorkHandler(object sender, global::System.ComponentModel.DoWorkEventArgs args)
{
    Compatlib.System.ComponentModel.DoWorkEventArgs newArgs = new Compatlib.System.ComponentModel.DoWorkEventArgs();
    newArgs.args = args;
    this._fDoWork._1_1fire(this, newArgs);
}
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.BackgroundWorker]

} // end of class: BackgroundWorker

} // end of namespace: Compatlib.System.ComponentModel
