// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace Compatlib.System.ComponentModel {
public class DoWorkEventHandler: global::Compatlib.System.EventHandler {
public void @this(global::Compatlib.System.Object n1, global::Compatlib.System.String n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.DoWorkEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
    base.@this(n1, n2);
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.DoWorkEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.System.ComponentModel.DoWorkEventHandler]
//XMLVM_END_WRAPPER[Compatlib.System.ComponentModel.DoWorkEventHandler]

} // end of class: DoWorkEventHandler

} // end of namespace: Compatlib.System.ComponentModel
