// Automatically generated by xmlvm2csharp. Do not edit!

using org.xmlvm;

namespace Compatlib.Microsoft.Devices.Sensors {
public class ReadingChangedEventHandler: global::Compatlib.System.EventHandler {
public new void @this(Compatlib.System.Object n1, Compatlib.System.String n2){
//XMLVM_BEGIN_WRAPPER[Compatlib.Microsoft.Devices.Sensors.ReadingChangedEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
    base.@this(n1, n2);
//XMLVM_END_WRAPPER[Compatlib.Microsoft.Devices.Sensors.ReadingChangedEventHandler: void <init>(Compatlib.System.Object, Compatlib.System.String)]
}

//XMLVM_BEGIN_WRAPPER[Compatlib.Microsoft.Devices.Sensors.ReadingChangedEventHandler]
//XMLVM_END_WRAPPER[Compatlib.Microsoft.Devices.Sensors.ReadingChangedEventHandler]

} // end of class: ReadingChangedEventHandler

} // end of namespace: Compatlib.Microsoft.Devices.Sensors
