#import "java_lang_String.h"
#import "plugins_zip_ZipArchiveDelegate.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "plugins_zip_ZipArchive.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation ZipArchive (cat_plugins_zip_ZipArchive)

- (void) __init_plugins_zip_ZipArchive__
{
}

- (int) createZipFile2___java_lang_String :(java_lang_String*)file
{
	return [self CreateZipFile2:file];
}

- (int) createZipFile2___java_lang_String_java_lang_String :(java_lang_String*)file :(java_lang_String*)pass
{
	return [self CreateZipFile2:file Password:pass];
}

- (int) addFileToZip___java_lang_String_java_lang_String :(java_lang_String*)file :(java_lang_String*)newname
{
	return [self addFileToZip:file newname:newname];
}

- (int) closeZipFile2__
{
	return [self CloseZipFile2];
}

- (int) unzipOpenFile___java_lang_String :(java_lang_String*)file
{
	return [self UnzipOpenFile:file];
}

- (int) unzipOpenFile___java_lang_String_java_lang_String :(java_lang_String*)file :(java_lang_String*)pass
{
	return [self UnzipOpenFile:file Password:pass];
}

- (int) unzipFileTo___java_lang_String_boolean :(java_lang_String*)path :(int)overwrite
{
	return [self UnzipFileTo:path overWrite:overwrite];
}

- (int) unzipCloseFile__
{
	return [self UnzipCloseFile];
}

- (plugins_zip_ZipArchiveDelegate*) getDelegate__
{
	return_XMLVM(delegate)
}

- (void) setDelegate___plugins_zip_ZipArchiveDelegate :(plugins_zip_ZipArchiveDelegate*)newdelegate
{
	XMLVM_PROPERTY(delegate,newdelegate)
}

@end
