// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.zip {
public class Adler32: global::java.lang.Object,global::java.util.zip.Checksum {
private long updateImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Adler32: long updateImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Adler32: long updateImpl(byte[], int, int, long)]
}

private long updateByteImpl(int n1, long n2){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Adler32: long updateByteImpl(int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Adler32: long updateByteImpl(int, long)]
}

//XMLVM_BEGIN_WRAPPER[java.util.zip.Adler32]
//XMLVM_END_WRAPPER[java.util.zip.Adler32]

} // end of class: Adler32

} // end of namespace: java.util.zip
