// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.zip {
public class CRC32: global::java.lang.Object,global::java.util.zip.Checksum {
private long updateImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.CRC32: long updateImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.CRC32: long updateImpl(byte[], int, int, long)]
}

private long updateByteImpl(sbyte n1, long n2){
//XMLVM_BEGIN_WRAPPER[java.util.zip.CRC32: long updateByteImpl(byte, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.CRC32: long updateByteImpl(byte, long)]
}

//XMLVM_BEGIN_WRAPPER[java.util.zip.CRC32]
//XMLVM_END_WRAPPER[java.util.zip.CRC32]

} // end of class: CRC32

} // end of namespace: java.util.zip
