// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.zip {
public class Deflater: global::java.lang.Object {
private static void oneTimeInitialization(){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void oneTimeInitialization()]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void oneTimeInitialization()]
}

private int deflateImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4, int n5){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: int deflateImpl(byte[], int, int, long, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: int deflateImpl(byte[], int, int, long, int)]
}

private void endImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void endImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void endImpl(long)]
}

private int getAdlerImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: int getAdlerImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: int getAdlerImpl(long)]
}

private long getTotalInImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: long getTotalInImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: long getTotalInImpl(long)]
}

private long getTotalOutImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: long getTotalOutImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: long getTotalOutImpl(long)]
}

private void resetImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void resetImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void resetImpl(long)]
}

private void setDictionaryImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void setDictionaryImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void setDictionaryImpl(byte[], int, int, long)]
}

private void setLevelsImpl(int n1, int n2, long n3){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void setLevelsImpl(int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void setLevelsImpl(int, int, long)]
}

private void setInputImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: void setInputImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: void setInputImpl(byte[], int, int, long)]
}

private long createStream(int n1, int n2, bool n3){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater: long createStream(int, int, boolean)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Deflater: long createStream(int, int, boolean)]
}

//XMLVM_BEGIN_WRAPPER[java.util.zip.Deflater]
//XMLVM_END_WRAPPER[java.util.zip.Deflater]

} // end of class: Deflater

} // end of namespace: java.util.zip
