// Automatically generated by xmlvm2csharp (do not edit).

using global::org.xmlvm;
namespace java.util.zip {
public class Inflater: global::java.lang.Object {
private static void oneTimeInitialization(){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: void oneTimeInitialization()]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: void oneTimeInitialization()]
}

private long createStream(bool n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: long createStream(boolean)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: long createStream(boolean)]
}

private void endImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: void endImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: void endImpl(long)]
}

private int getAdlerImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: int getAdlerImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: int getAdlerImpl(long)]
}

private long getTotalInImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: long getTotalInImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: long getTotalInImpl(long)]
}

private long getTotalOutImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: long getTotalOutImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: long getTotalOutImpl(long)]
}

private int inflateImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: int inflateImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: int inflateImpl(byte[], int, int, long)]
}

private void resetImpl(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: void resetImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: void resetImpl(long)]
}

private void setDictionaryImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: void setDictionaryImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: void setDictionaryImpl(byte[], int, int, long)]
}

private void setInputImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3, long n4){
//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater: void setInputImpl(byte[], int, int, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[java.util.zip.Inflater: void setInputImpl(byte[], int, int, long)]
}

//XMLVM_BEGIN_WRAPPER[java.util.zip.Inflater]
//XMLVM_END_WRAPPER[java.util.zip.Inflater]

} // end of class: Inflater

} // end of namespace: java.util.zip
